### ISSUE TITLE
自动去重算法优化

### ISSUE THREAD

**Issue by AnkioTomas** [AutoAccountingOrg/AutoAccounting#100]
目前的自动去重是用户点击记账以后才进行去重，比较麻烦。

1.  所有的记账信息加入队列，按照队列先来后到执行
2.  将任务加入队列之前，对于当前的任务进行检查，如果发现疑似为重复账单的就直接合并（运行中通知UI）
3.  考虑到记账服务的稳定性，将队列放到C++部分处理

**Comment by AnkioTomas** [comment]
如果一个规则，没有给出对应的资产信息，应该认为是重复的（即可以根据金额等信息来判断是同一类）

**Comment by KDreamelf** [comment]
如果一个规则确定了资产，一个规则确定了分类，一个规则确定了金额，能不能将这些数据智能合并？有冲突挑出来让用户解决。并显示什么数据是什么规则提供的。这样用户也知道什么规则靠谱什么规则不行。也不至于启用一堆规则叠叠乐了。
