### ISSUE TITLE
适配失败

### ISSUE THREAD

**Issue by beipuo** [AutoAccountingOrg/AutoAccounting#107]
微信红包不能识别，lsp里强行停止微信，显示自动记账正在适配，适配失败
[log.txt](https://github.com/AutoAccountingOrg/AutoAccounting/files/15228700/log.txt)

**Comment by AnkioTomas** [comment]
微信版本？
自动记账版本？
规则版本？

**Comment by beipuo** [comment]
微信版本：8.0.44
自动记账版本4.0.0-beta8
规则版本：0.2.1

**Comment by AnkioTomas** [comment]
请提供微信的lsp日志

**Comment by beipuo** [comment]
beta10依旧存在，但微信更新至8.0.49，适配成功
