### ISSUE TITLE
[Feature Request] 记账应用支持 Firefly iii

### ISSUE THREAD

**Issue by sgpublic** [AutoAccountingOrg/AutoAccounting#180]
[Firefly iii](https://github.com/firefly-iii/firefly-iii) 是个自托管的个人财务管理平台，记账是通过调用 http 接口的方式，看大佬是否有兴趣适配一波。

PS：其实我是打算自己写了提 PR 的，因为按照我的理解适配起来应该不难，对接钱迹其实也是调用 url，但奈何大佬这项目太激进了用的 Android Studio Canary，举例来说截止于 issue 创建的现在，必须使用 Android Studio 2024.1.1 Canary 6 才能把项目跑起来，高了低了都不行（悲

**Comment by AnkioTomas** [comment]
自动记账v4不再将记账应用内置了
可以自己新开一个项目接入自动记账的sdk即可

具体细节可以参考 demo 和 钱迹补丁

**Comment by AnkioTomas** [comment]
之所以用Canary版，是因为我想用一个as的新功能，结果稳定版还没发....然后就在Canary的路上越走越远........

**Comment by sgpublic** [comment]
明白了，我研究研究

**Comment by sgpublic** [comment]
@AnkioTomas 佬，我想确认一下现在适配自动记账是只需要用 HTTP 接口就行了对吗
