### ISSUE TITLE
账单合并显示存在问题

### ISSUE THREAD

**Issue by z1298808165** [AutoAccountingOrg/AutoAccounting#187]
如下图所示，账单合并显示的好像都是测试数据
![1715399706987_d](https://github.com/AutoAccountingOrg/AutoAccounting/assets/25720725/5a5d4eb3-5404-411d-b566-164787885c9e)

**Comment by DYS7516461** [comment]
兄弟，你的分类是怎么设置的，我的分类数据不能自己添加啊

**Comment by z1298808165** [comment]
> 兄弟，你的分类是怎么设置的，我的分类数据不能自己添加啊

分类？在钱迹里添加呀，同步到自动记账的

**Comment by DYS7516461** [comment]
我用的lsp，钱迹补丁也安装了，打开钱迹也提示钱迹补丁适配了，但是自动记账还是提示未设置记账应用，你有没有遇到过

**Comment by AnkioTomas** [comment]
打开钱迹 - 划开侧栏 - 钱迹补丁 - 自动记账主开关 - 打开
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by DYS7516461** [comment]
可以了，感谢
