### ISSUE TITLE
微信支付数据缺少信息

### ISSUE THREAD

**Issue by taigongzhaihua** [AutoAccountingOrg/AutoAccounting#20]
微信支付数据缺少卡片标题的商户名数据，数据中title为点进微信支付前显示的的内容"已支付xxx"

**Comment by taigongzhaihua** [comment]
![Screenshot_2024-04-10-22-28-08-911_com tencent mm](https://github.com/AutoAccountingOrg/AutoAccounting/assets/18004386/61f34b69-f393-46e6-ac4a-e6d18b64cf4d)

**Comment by AnkioTomas** [comment]
在自动记账设置中打开调试模式，然后支付一下触发后，发我lsp日志
