### ISSUE TITLE
beat 8&9均发现该bug

### ISSUE THREAD

**Issue by yanyanxinshi** [AutoAccountingOrg/AutoAccounting#208]
![c895e9a1f599fad7289560816f7282d](https://github.com/AutoAccountingOrg/AutoAccounting/assets/81509046/f163d78b-7f57-4add-83ce-b5ce6ea77fbe)

在软件中记账，打开钱迹后，显示该内容。

[log.txt](https://github.com/AutoAccountingOrg/AutoAccounting/files/15284806/log.txt)

手机型号：小米10
系统：澎湃os

**Comment by AnkioTomas** [comment]
非钱迹会员的bug，已在下个版本修复
