### ISSUE TITLE
bata10 交易产生时没有悬浮窗

### ISSUE THREAD

**Issue by z1298808165** [AutoAccountingOrg/AutoAccounting#227]
交易产生时能读取到数据，但没有悬浮窗出现，手动点击记账正常
[lsplog.txt](https://github.com/AutoAccountingOrg/AutoAccounting/files/15289746/lsplog.txt)

**Comment by AnkioTomas** [comment]
补充自动记账的log

**Comment by z1298808165** [comment]
> 补充自动记账的log

[daemon .log](https://github.com/AutoAccountingOrg/AutoAccounting/files/15289987/daemon.log)
[log.txt](https://github.com/AutoAccountingOrg/AutoAccounting/files/15289989/log.txt)
