### ISSUE TITLE
beta10 打开微信无限跳转自动记账

### ISSUE THREAD

**Issue by beipuo** [AutoAccountingOrg/AutoAccounting#230]
打开微信，同意跳转自动记账后，再次打开微信，无限跳转自动记账。
自动记账我：beta10
微信：8.0.49
规则：官方0.2.1
[log.txt](https://github.com/AutoAccountingOrg/AutoAccounting/files/15301208/log.txt)

**Comment by AnkioTomas** [comment]
一个已知的bug，预计下个版本解决

**Comment by wzgrx** [comment]
想知道修复了吗
