### ISSUE TITLE
建议授权文件更换目录

### ISSUE THREAD

**Issue by z1298808165** [AutoAccountingOrg/AutoAccounting#235]
`/storage/emulated/0/Android/data/net.ankio.auto.xposed/cache/shell/` 目前授权文件似乎都在这里面，但是一些授权了root或有权限的垃圾清理软件是会清理软件的`cache`目录，故而会造成授权信息丢失。

目前测试的结果是会导致使用微信时不停的弹进自动记账界面，手动执行`/storage/emulated/0/Android/data/net.ankio.auto.xposed/cache/shell/` 目录下的`starter.sh`文件可解决该情况

**Comment by AnkioTomas** [comment]
- ADB的权限最高只能访问app的外置缓存目录，不能访问内部数据目录
- `/data/local/tmp` 不适合作为长期存储数据的位置
- 找不到更合适的位置
