### ISSUE TITLE
在用bata10遇到的问题

### ISSUE THREAD

**Issue by JackJia000** [AutoAccountingOrg/AutoAccounting#238]
1，一直不弹窗，也就不记账，只能手动添加账单。不知道哪的问题
2, 似乎个人创建的规则不起作用，只能用服务器规则
3,账单去重功能，似乎逻辑有问题。金额跟商户一致就直接写一块儿了。个人觉得，首先判断的应该是日期，日期一致再判断金额跟商户是否一致，一致再去重

**Comment by AnkioTomas** [comment]
1. 是beta10特有的bug,可以回退到beta9
2. 需要提供更多的信息：例如你的规则截图，你测试的数据截图，相关的分类日志截图
3. 去重功能在重构中
