### ISSUE TITLE
【重要】更多记账应用适配

### ISSUE THREAD

**Issue by AnkioTomas** [AutoAccountingOrg/AutoAccounting#319]
自动记账beta11之后，通信模式有极大的改变，建议各位开发者暂停适配工作。
等正式版发布后再进行适配。

**Comment by LOVENVE** [comment]
![LSPosed_2024-09-22T13_00_12.884699.zip](https://github.com/user-attachments/files/17088371/LSPosed_2024-09-22T13_00_12.884699.zip)

大佬这个版本不记账啊

**Comment by AnkioTomas** [comment]
> ![LSPosed_2024-09-22T13_00_12.884699.zip](https://github.com/user-attachments/files/17088371/LSPosed_2024-09-22T13_00_12.884699.zip)
> 
> 大佬这个版本不记账啊

有问题新开issue，还有你要等github的图片上传完毕再提交，不然看不见图
