### ISSUE TITLE
建议数据页新增删除数据功能以及LSP日志开关

### ISSUE THREAD

**Issue by z1298808165** [AutoAccountingOrg/AutoAccounting#322]
1.随着使用时间，数据页的数据已经逐渐累积变多，希望可以新增一个删除数据的按钮，并支持删除过滤后的指定数据。

2.因为会使用其它lsp模块，有时候需要反馈LSP日志，但因为自动记账的日志过多且很多都是隐私信息（微信聊天记录），导致发送日志的时候比较麻烦，容易泄露隐私，故希望可以有个开关可以控制。

**Comment by AnkioTomas** [comment]
1. 数据页面的数据是自动删除的，阈值是500
2. 这个功能有的，公测阶段强制关闭了。
