### ISSUE TITLE
自动分类规则

### ISSUE THREAD

**Issue by LanFeng11** [AutoAccountingOrg/AutoAccounting#357]
分类名称和使用账本名称大多不一样，官方默认适配度低，甚至一部分人不知道官方规则库带自动分类规则，分类规则需更方便的自定义
建议
1.官方自动分类规则需要一个修改途径，一默认规则几乎无法匹配，二不需要频繁更新，三单靠自动生成分类很麻烦，规则容易又多又乱，建议还是用JS编辑，APP内或者本地JS文件可修改
2.自定义分类规则显示默认规则，可以删除，点击可查看支持的分类 ，方便不会修改JS的修改钱迹分类
3.自定义分类规则匹配优先级比默认规则高，可以批量删除，打开自动生成分类可能会生成大量规则
4.编辑bug，选择完分类确定之后，分类弹窗还存在。再次修改编辑无法保存

**Comment by AnkioTomas** [comment]
1. 用分类映射会不会好一点？

**Comment by LanFeng11** [comment]
感觉自动分类就简单不了，少说也有十多个分类，用分类映射也要设置很多，懒人设置有一个办法，按钱迹默认分类来做规则

**Comment by LanFeng11** [comment]
分类映射对我们来说更友好，不知道难不难做，设置肯定更方便更人性化
