### ISSUE TITLE
金额识别错误

### ISSUE THREAD

**Issue by 1587110498** [AutoAccountingOrg/AutoAccounting#377]
数据是正确的，规则也是正确的，但是识别的金额不正确，例如19.8元识别成18.79元。会丢失精度

**Comment by AnkioTomas** [comment]
请提供可供复现的数据

**Comment by 1587110498** [comment]
![f94dddb8ed9d8dbe39e70f607da31145](https://github.com/AutoAccountingOrg/AutoAccounting/assets/169517704/220a4eb4-190c-4bbf-8936-e7d0e7eb433a)
自动记账版本：beta9
规则v0.2.3
