### ISSUE TITLE
规则无法更新

### ISSUE THREAD

**Issue by ttt789-ppo** [AutoAccountingOrg/AutoAccounting#456]
无法更新规则，应该是网盘地址错了，还有建议加个导入规则.zip功能
![Uploading Screenshot_2024-09-04-08-05-04-36_696fc9dfea9e2f51729e0646b2031c10.png…]()

**Comment by AnkioTomas** [comment]
那是beta13（尚未发布的版本）的规则

**Comment by ttt789-ppo** [comment]
> 那是beta13（尚未发布的版本）的规则

但是我用beta12官方规则那点规则更新没反应，就一个检查更新中的toast提示，然后什么都没发生，规则那还是None
