### ISSUE TITLE
已无法下载到最新版本。

### ISSUE THREAD

**Issue by KDreamelf** [AutoAccountingOrg/AutoAccounting#473]
APP自带更新失效
APP内跳转的github仓库和那个仓库留的连接指向的都不是这个仓库。
这个仓库都是我故意触发一次报错导致文档404跳转首页才找到的。
然后我找了下持续构建版，这玩意的下载链接也挂了。
现在我用的还是涅槃3.3.4版本。记账经常无法唤醒（但事后找到APP记录测试规则都是OK的，自启动也给了，甚至灭霸模块开了保后台）

**Comment by AnkioTomas** [comment]
自动记账4.0尚未发布正式版
