### ISSUE TITLE
无资产下，在账单编辑页面点击资产选择后，无法返回或退出

### ISSUE THREAD

**Issue by lsr0LSR** [AutoAccountingOrg/AutoAccounting#490]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

由于未在钱迹之中设置资产，导致在账单编辑时进入资产选择界面后显示空空如也，无法操作，无法返回和退出

### 重现步骤

```bash
1.不设置任何资产
2.以任意方式进入账单编辑界面（触发自动记账或手动在app中选择账单）
3.点击资产
4.显示空空如也，无法返回或退出，只能杀死APP，且在触发自动记账的悬浮窗下，无法进行任何操作，只能重启手机。

另，如果在钱迹中设置了资产，在账单资产选择界面仍不能手动返回和退出，但可以选择已有的资产后自动返回
```

### 相关环境说明

自动记账4.0.0-Canary.20240915094555 - Xposed(212)
钱迹4.1.0(951)
lsp v7075
andriod 14

### 日志内容

此问题为UI bug，无相关操作日志
![IMG_20240916_103354](https://github.com/user-attachments/assets/967326b7-2b01-422d-921b-46282b471bb5)
![Screenshot_2024-09-16-10-32-36-97_696fc9dfea9e2f51729e0646b2031c10](https://github.com/user-attachments/assets/f68d6bc2-0079-40a3-acf8-83d0de141c0a)

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
可以在设置中关闭资产管理
