### ISSUE TITLE
重复弹窗

### ISSUE THREAD

**Issue by Mingyu2333** [AutoAccountingOrg/AutoAccounting#531]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

已被记账的数据重复弹窗出现

### 重现步骤

```bash
正常使用手机不定时弹出已被记账的数据弹窗，尝试重启后仍然复现
偶现打开自动记账时弹出已被记账的数据弹窗，待复现后再补充上传相关日志
```

### 相关环境说明

4.0.0-Canary.20240920151104 - Xposed
hyperos/A14

### 日志内容

[log.txt](https://github.com/user-attachments/files/17082145/log.txt)
8:35和8:46分别出现弹窗，更早数据未记录时间
相关截图：
![Screenshot_2024-09-21-08-46-05-720_com miui home](https://github.com/user-attachments/assets/714c80ca-532e-47ab-ae67-d7e689f97343)
`
![Screenshot_2024-09-21-08-35-08-202_com coolapk market](https://github.com/user-attachments/assets/6c945282-cc1f-4bcf-b038-6265a1eddde6)
`

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by Mingyu2333** [comment]
就在刚刚（10:30左右）玩游戏疯狂弹出已被记账的数据弹窗相关日志
[log (1).txt](https://github.com/user-attachments/files/17082520/log.1.txt)

**Comment by AnkioTomas** [comment]
问题1，正在研究中。
问题2，微信只有部分数据可以获取到账单时间（主要是微信没有提供时间），其他的只能根据自动记账收到数据的时间生成。

**Comment by Mingyu2333** [comment]
好的，辛苦大大了，这个bug在版本更新前未遇到相关情况，就在刚刚又有一组疯狂弹窗，稍微看了下日志，时间为10:52分，相关日志
[log (2).txt](https://github.com/user-attachments/files/17082583/log.2.txt)

**Comment by Mingyu2333** [comment]
补充一份4.0.0-Canary.20240921102533更新后的日志，这次为打开自动记账时弹出，好像每次都是自动记账服务启动时候造成的重复弹窗。弹窗时间23:31，之前仍有多次复现，但未记录
[log(3).txt](https://github.com/user-attachments/files/17084658/log.3.txt)

**Comment by AnkioTomas** [comment]
> 补充一份4.0.0-Canary.20240921102533更新后的日志，这次为打开自动记账时弹出，好像每次都是自动记账服务启动时候造成的重复弹窗。弹窗时间23:31，之前仍有多次复现，但未记录 [log(3).txt](https://github.com/user-attachments/files/17084658/log.3.txt)

我这边完全复现不了，下次把lsp日志也一并带上

**Comment by Mingyu2333** [comment]
> > 补充一份4.0.0-Canary.20240921102533更新后的日志，这次为打开自动记账时弹出，好像每次都是自动记账服务启动时候造成的重复弹窗。弹窗时间23:31，之前仍有多次复现，但未记录 [log(3).txt](https://github.com/user-attachments/files/17084658/log.3.txt)
> 
> 我这边完全复现不了，下次把lsp日志也一并带上

01:14分左右，弹出此窗口
![Screenshot_2024-09-22-01-15-10-273_com dragon read](https://github.com/user-attachments/assets/ad1d3175-5c6c-47de-82b0-edbbd5926e8d)
日志：
[log.txt](https://github.com/user-attachments/files/17085130/log.txt)
[LSPosed_2024-09-22T01_19_37.516229.zip](https://github.com/user-attachments/files/17085131/LSPosed_2024-09-22T01_19_37.516229.zip)
自己的模块列表
![Screenshot_2024-09-22-01-23-36-460_com android shell](https://github.com/user-attachments/assets/78f30e01-bbf4-47fb-9c9a-af79fe3de8ea)

**Comment by AnkioTomas** [comment]
禁用AppRetention模块看看，感觉这个模块是负优化.....

**Comment by Mingyu2333** [comment]
> 禁用AppRetention模块看看，感觉这个模块是负优化.....

已经禁用，但是在11:22分又出现了，这是相关日志
[LSPosed_2024-09-22T11_23_59.675183.zip](https://github.com/user-attachments/files/17088144/LSPosed_2024-09-22T11_23_59.675183.zip)
[log(1)(2).txt](https://github.com/user-attachments/files/17088141/log.1.2.txt)

**Comment by AnkioTomas** [comment]
> > 禁用AppRetention模块看看，感觉这个模块是负优化.....
> 
> 已经禁用，但是在11:22分又出现了，这是相关日志 [LSPosed_2024-09-22T11_23_59.675183.zip](https://github.com/user-attachments/files/17088144/LSPosed_2024-09-22T11_23_59.675183.zip) [log(1)(2).txt](https://github.com/user-attachments/files/17088141/log.1.2.txt)

复现到这个问题了，我觉得我应该是修复了....
https://github.com/AutoAccountingOrg/AutoAccounting/commit/07cc5b867f5fdc880c7cde79d4d66a839dd1f8bc
等构建完成，试下这个版本：https://github.com/AutoAccountingOrg/AutoAccounting/actions/runs/10977994919

**Comment by AnkioTomas** [comment]
https://github.com/AutoAccountingOrg/AutoAccounting/releases/tag/4.0.0-Canary.20240922033757

**Comment by Mingyu2333** [comment]
> > > 禁用AppRetention模块看看，感觉这个模块是负优化.....
> > 
> > 
> > 已经禁用，但是在11:22分又出现了，这是相关日志 [LSPosed_2024-09-22T11_23_59.675183.zip](https://github.com/user-attachments/files/17088144/LSPosed_2024-09-22T11_23_59.675183.zip) [log(1)(2).txt](https://github.com/user-attachments/files/17088141/log.1.2.txt)
> 
> 复现到这个问题了，我觉得我应该是修复了.... [07cc5b8](https://github.com/AutoAccountingOrg/AutoAccounting/commit/07cc5b867f5fdc880c7cde79d4d66a839dd1f8bc) 等构建完成，试下这个版本：https://github.com/AutoAccountingOrg/AutoAccounting/actions/runs/10977994919

好像是解决了，目前重启自动记账多次都没有弹窗了。辛苦大佬了
