### ISSUE TITLE
[Bug][Rule][DATA]com.eg.android.AlipayGphone

### ISSUE THREAD

**Issue by wangxixi789** [AutoAccountingOrg/AutoAccounting#541]
## 规则
[{"mk":240962003843200002,"st":1,"isSc":0,"appId":"","mct":1726936723000,"pl":"{\"templateType\":\"BN\",\"commandType\":\"UPDATE\",\"withPushNfc\":\"Y\",\"expireLink\":\"\",\"msgType\":\"TODO\",\"icon\":\"https://gw.alipayobjects.com/mdn/rms_f96971/afts/img/A*leNcS41oUu0AAAAAAAAAAABkARQnAQ\",\"link\":\"alipays://platformapi/startapp?appId\u003d20000003\u0026actionType\u003dtoBillDetails\u0026tradeNO\u003d20240922019130175990800063578278\u0026bizType\u003dYEB?tagid\u003dMB_SEND_PUSH_WALLET_NEW\",\"businessId\":\"PAY_HELPER_CARD_2088632159664804\",\"msgId\":\"cb6e19edc52bb2fe10f824c366d7367f00480\",\"templateCode\":\"00059_00094_zfzs001\",\"templateId\":\"WALLET-BILL@BLPaymentHelper\",\"title\":\"红包奖励发放\",\"content\":\"{\\\"status\\\":\\\"理财奖励到账\\\",\\\"date\\\":\\\"09月22日\\\",\\\"amountTip\\\":\\\"\\\",\\\"money\\\":\\\"0.05\\\",\\\"unit\\\":\\\"元\\\",\\\"infoTip\\\":\\\"\\\",\\\"failTip\\\":\\\"\\\",\\\"goto\\\":\\\"alipays://platformapi/startapp?appId\u003d20000003\u0026actionType\u003dtoBillDetails\u0026tradeNO\u003d20240922019130175990800063578278\u0026bizType\u003dYEB\\\",\\\"content\\\":[{\\\"title\\\":\\\"交易对象：\\\",\\\"content\\\":\\\"余额宝\\\"}],\\\"ad\\\":[],\\\"actions\\\":[{\\\"name\\\":\\\"\\\",\\\"url\\\":\\\"\\\"},{\\\"name\\\":\\\"查看详情\\\",\\\"url\\\":\\\"alipays://platformapi/startapp?appId\u003d20000003\u0026actionType\u003dtoBillDetails\u0026tradeNO\u003d20240922019130175990800063578278\u0026bizType\u003dYEB\\\"}]}\",\"linkName\":\"\",\"bizName\":\"支付助手\",\"msgCategory\":\"bill\",\"scm\":\"27.gotone.card.cb6e19edc52bb2fe10f824c366d7367f00480.MB_SEND_PH_NEW.null.payment_assist.10090.10099..\",\"assistInfo\":\"{\\\"showInFriendTab\\\":false,\\\"icon\\\":\\\"https://gw.alipayobjects.com/mdn/rms_f96971/afts/img/A*ZapXT6AjvG0AAAAAAAAAAABkARQnAQ\\\",\\\"reminderType\\\":\\\"point\\\",\\\"hiddenMsgHeader\\\":false,\\\"title\\\":\\\"支付助手\\\",\\\"reminderTypeModifyEnable\\\":false,\\\"assistId\\\":\\\"payment_assist\\\",\\\"desc\\\":\\\"支付宝资金变动通知\\\"}\",\"ih\":\"{\\\"extInfo\\\":{},\\\"iid\\\":\\\"105\\\",\\\"ioty\\\":\\\"aor\\\",\\\"itemBasicInfo\\\":{\\\"dn\\\":\\\"服务提醒\\\",\\\"ic\\\":\\\"https://gw.alipayobjects.com/zos/bmw-prod/b96c31e0-64ba-4cbb-9a64-73ff17d701fd.webp\\\",\\\"lk\\\":\\\"alipays://platformapi/startapp?appId\u003d20000235\u0026source\u003dfriendTab\\\"},\\\"itemUserRelation\\\":{\\\"ilf\\\":\\\"N\\\",\\\"uc\\\":{\\\"top\\\":\\\"0\\\"},\\\"version\\\":0},\\\"ity\\\":\\\"105\\\",\\\"moty\\\":\\\"u\\\",\\\"msgInfo\\\":{\\\"bm\\\":\\\"红包奖励发放￥0.05\\\",\\\"cmid\\\":\\\"cb6e19edc52bb2fe10f824c366d7367f00480\\\",\\\"lmt\\\":1726936723112,\\\"msrid\\\":\\\"00059_00094_zfzs001\\\",\\\"ncs\\\":\\\"N\\\",\\\"rps\\\":\\\"num\\\",\\\"sam\\\":\\\"Y\\\",\\\"ssrid\\\":\\\"PAY_HELPER_CARD_2088632159664804\\\",\\\"urn\\\":1}}\",\"bizMonitor\":\"{\\\"serviceCode\\\":\\\"MB_SEND_PH_NEW\\\",\\\"bizName\\\":\\\"\\\",\\\"createTime\\\":1726936723150,\\\"businessId\\\":\\\"PAY_HELPER_CARD_2088632159664804\\\",\\\"messageId\\\":\\\"cb6e19edc52bb2fe10f824c366d7367f00480\\\",\\\"messageTitle\\\":\\\"红包奖励发放\\\",\\\"pid\\\":\\\"2088721233855772\\\",\\\"templateId\\\":\\\"WALLET-BILL@BLPaymentHelper\\\",\\\"status\\\":\\\"\\\"}\",\"languageType\":\"zh-Hans\",\"subscribeConfig\":\"0\",\"gmtCreate\":1726936723112,\"gmtValid\":2042296723108,\"operate\":\"SEND\",\"templateName\":\"支付助手\",\"homePageTitle\":\"红包奖励发放￥0.05\",\"status\":\"\",\"extraInfo\":\"{\\\"topSubContent\\\":\\\"转入成功\\\",\\\"preValue\\\":\\\"￥\\\",\\\"languageType\\\":\\\"zh-Hans\\\",\\\"isPaymentMsg\\\":true,\\\"assistName2\\\":\\\"\\\",\\\"assistName3\\\":\\\"\\\",\\\"assistName1\\\":\\\"交易对象\\\",\\\"templateId\\\":\\\"WALLET-FWC@remindNumber\\\",\\\"content\\\":\\\"0.05\\\",\\\"linkName\\\":\\\"\\\",\\\"assistMsg3\\\":\\\"\\\",\\\"sceneExt2\\\":{\\\"sceneUrl\\\":\\\"alipays://platformapi/startapp?appId\u003d20000003\u0026actionType\u003dtoBillDetails\u0026tradeNO\u003d20240922019130175990800063578278\u0026bizType\u003dYEB\\\",\\\"sceneType\\\":\\\"nativeApp\\\",\\\"sceneName\\\":\\\"余额宝\\\",\\\"sceneIcon\\\":\\\"https://gw.alipayobjects.com/mdn/rms_b03cca/afts/img/A*YczITbg-JhMAAAAAAAAAAAAAARQnAQ\\\"},\\\"assistMsg2\\\":\\\"\\\",\\\"assistMsg1\\\":\\\"余额宝\\\",\\\"assistName4\\\":\\\"\\\",\\\"assistMsg5\\\":\\\"\\\",\\\"assistMsg4\\\":\\\"\\\",\\\"assistName5\\\":\\\"\\\",\\\"buttonLink\\\":\\\"\\\",\\\"cardAdInfo\\\":{\\\"p116\\\":{\\\"bizMonitor\\\":{\\\"marketingUniqueId\\\":\\\"MUc92881da752d4cf3a5dce4e0e7688bb1\\\",\\\"outBizId\\\":\\\"LIFE_MSG_TEXT|AMTT_drm|-\\\",\\\"marketingRuleId\\\":\\\"MRe1083c96277549ee85623566b185810c\\\",\\\"style\\\":\\\"actionLine2\\\",\\\"marketingItemId\\\":\\\"MI5d3aa42b820144c78fdcdf18e14b25e9\\\"},\\\"expireTime\\\":1758472723149,\\\"marketingUniqueId\\\":\\\"MUc92881da752d4cf3a5dce4e0e7688bb1\\\",\\\"minClientVersion\\\":\\\"10.1.98\\\",\\\"recommendTemplateId\\\":\\\"actionLine2\\\",\\\"viewInfo\\\":{\\\"btnName\\\":\\\"支付奖励\\\",\\\"actionType\\\":\\\"link\\\",\\\"tagIcon\\\":\\\"https://mdn.alipayobjects.com/huamei_cke3ep/afts/img/A*s1xhTYe-_PQAAAAAAAAAAAAADk1-AQ/original\\\",\\\"tagColor\\\":\\\"#FF6011\\\",\\\"actionUrl\\\":\\\"alipays://platformapi/startapp?appId\u003d68687805\u0026url\u003dhttps%3A%2F%2Frender.alipay.com%2Fp%2Fyuyan%2F180020380000000023%2Fhome-page.html%3Fsource%3Ddzyyxiaoxi%26chInfo%3Ddzyyxiaoxi\\\",\\\"tag\\\":\\\"你有2561积分可使用\\\"}}}}\"}"}]
## 说明
应该是收入，但是识别成转账了
## 数据
```
[{"mk":240962003843200002,"st":1,"isSc":0,"appId":"","mct":1726936723000,"pl":"{\"templateType\":\"BN\",\"commandType\":\"UPDATE\",\"withPushNfc\":\"Y\",\"expireLink\":\"\",\"msgType\":\"TODO\",\"icon\":\"https://gw.alipayobjects.com/mdn/rms_f96971/afts/img/A*leNcS41oUu0AAAAAAAAAAABkARQnAQ\",\"link\":\"alipays://platformapi/startapp?appId\u003d20000003\u0026actionType\u003dtoBillDetails\u0026tradeNO\u003d20240922019130175990800063578278\u0026bizType\u003dYEB?tagid\u003dMB_SEND_PUSH_WALLET_NEW\",\"businessId\":\"PAY_HELPER_CARD_2088632159664804\",\"msgId\":\"cb6e19edc52bb2fe10f824c366d7367f00480\",\"templateCode\":\"00059_00094_zfzs001\",\"templateId\":\"WALLET-BILL@BLPaymentHelper\",\"title\":\"红包奖励发放\",\"content\":\"{\\\"status\\\":\\\"理财奖励到账\\\",\\\"date\\\":\\\"09月22日\\\",\\\"amountTip\\\":\\\"\\\",\\\"money\\\":\\\"0.05\\\",\\\"unit\\\":\\\"元\\\",\\\"infoTip\\\":\\\"\\\",\\\"failTip\\\":\\\"\\\",\\\"goto\\\":\\\"alipays://platformapi/startapp?appId\u003d20000003\u0026actionType\u003dtoBillDetails\u0026tradeNO\u003d20240922019130175990800063578278\u0026bizType\u003dYEB\\\",\\\"content\\\":[{\\\"title\\\":\\\"交易对象：\\\",\\\"content\\\":\\\"余额宝\\\"}],\\\"ad\\\":[],\\\"actions\\\":[{\\\"name\\\":\\\"\\\",\\\"url\\\":\\\"\\\"},{\\\"name\\\":\\\"查看详情\\\",\\\"url\\\":\\\"alipays://platformapi/startapp?appId\u003d20000003\u0026actionType\u003dtoBillDetails\u0026tradeNO\u003d20240922019130175990800063578278\u0026bizType\u003dYEB\\\"}]}\",\"linkName\":\"\",\"bizName\":\"支付助手\",\"msgCategory\":\"bill\",\"scm\":\"27.gotone.card.cb6e19edc52bb2fe10f824c366d7367f00480.MB_SEND_PH_NEW.null.payment_assist.10090.10099..\",\"assistInfo\":\"{\\\"showInFriendTab\\\":false,\\\"icon\\\":\\\"https://gw.alipayobjects.com/mdn/rms_f96971/afts/img/A*ZapXT6AjvG0AAAAAAAAAAABkARQnAQ\\\",\\\"reminderType\\\":\\\"point\\\",\\\"hiddenMsgHeader\\\":false,\\\"title\\\":\\\"支付助手\\\",\\\"reminderTypeModifyEnable\\\":false,\\\"assistId\\\":\\\"payment_assist\\\",\\\"desc\\\":\\\"支付宝资金变动通知\\\"}\",\"ih\":\"{\\\"extInfo\\\":{},\\\"iid\\\":\\\"105\\\",\\\"ioty\\\":\\\"aor\\\",\\\"itemBasicInfo\\\":{\\\"dn\\\":\\\"服务提醒\\\",\\\"ic\\\":\\\"https://gw.alipayobjects.com/zos/bmw-prod/b96c31e0-64ba-4cbb-9a64-73ff17d701fd.webp\\\",\\\"lk\\\":\\\"alipays://platformapi/startapp?appId\u003d20000235\u0026source\u003dfriendTab\\\"},\\\"itemUserRelation\\\":{\\\"ilf\\\":\\\"N\\\",\\\"uc\\\":{\\\"top\\\":\\\"0\\\"},\\\"version\\\":0},\\\"ity\\\":\\\"105\\\",\\\"moty\\\":\\\"u\\\",\\\"msgInfo\\\":{\\\"bm\\\":\\\"红包奖励发放￥0.05\\\",\\\"cmid\\\":\\\"cb6e19edc52bb2fe10f824c366d7367f00480\\\",\\\"lmt\\\":1726936723112,\\\"msrid\\\":\\\"00059_00094_zfzs001\\\",\\\"ncs\\\":\\\"N\\\",\\\"rps\\\":\\\"num\\\",\\\"sam\\\":\\\"Y\\\",\\\"ssrid\\\":\\\"PAY_HELPER_CARD_2088632159664804\\\",\\\"urn\\\":1}}\",\"bizMonitor\":\"{\\\"serviceCode\\\":\\\"MB_SEND_PH_NEW\\\",\\\"bizName\\\":\\\"\\\",\\\"createTime\\\":1726936723150,\\\"businessId\\\":\\\"PAY_HELPER_CARD_2088632159664804\\\",\\\"messageId\\\":\\\"cb6e19edc52bb2fe10f824c366d7367f00480\\\",\\\"messageTitle\\\":\\\"红包奖励发放\\\",\\\"pid\\\":\\\"2088721233855772\\\",\\\"templateId\\\":\\\"WALLET-BILL@BLPaymentHelper\\\",\\\"status\\\":\\\"\\\"}\",\"languageType\":\"zh-Hans\",\"subscribeConfig\":\"0\",\"gmtCreate\":1726936723112,\"gmtValid\":2042296723108,\"operate\":\"SEND\",\"templateName\":\"支付助手\",\"homePageTitle\":\"红包奖励发放￥0.05\",\"status\":\"\",\"extraInfo\":\"{\\\"topSubContent\\\":\\\"转入成功\\\",\\\"preValue\\\":\\\"￥\\\",\\\"languageType\\\":\\\"zh-Hans\\\",\\\"isPaymentMsg\\\":true,\\\"assistName2\\\":\\\"\\\",\\\"assistName3\\\":\\\"\\\",\\\"assistName1\\\":\\\"交易对象\\\",\\\"templateId\\\":\\\"WALLET-FWC@remindNumber\\\",\\\"content\\\":\\\"0.05\\\",\\\"linkName\\\":\\\"\\\",\\\"assistMsg3\\\":\\\"\\\",\\\"sceneExt2\\\":{\\\"sceneUrl\\\":\\\"alipays://platformapi/startapp?appId\u003d20000003\u0026actionType\u003dtoBillDetails\u0026tradeNO\u003d20240922019130175990800063578278\u0026bizType\u003dYEB\\\",\\\"sceneType\\\":\\\"nativeApp\\\",\\\"sceneName\\\":\\\"余额宝\\\",\\\"sceneIcon\\\":\\\"https://gw.alipayobjects.com/mdn/rms_b03cca/afts/img/A*YczITbg-JhMAAAAAAAAAAAAAARQnAQ\\\"},\\\"assistMsg2\\\":\\\"\\\",\\\"assistMsg1\\\":\\\"余额宝\\\",\\\"assistName4\\\":\\\"\\\",\\\"assistMsg5\\\":\\\"\\\",\\\"assistMsg4\\\":\\\"\\\",\\\"assistName5\\\":\\\"\\\",\\\"buttonLink\\\":\\\"\\\",\\\"cardAdInfo\\\":{\\\"p116\\\":{\\\"bizMonitor\\\":{\\\"marketingUniqueId\\\":\\\"MUc92881da752d4cf3a5dce4e0e7688bb1\\\",\\\"outBizId\\\":\\\"LIFE_MSG_TEXT|AMTT_drm|-\\\",\\\"marketingRuleId\\\":\\\"MRe1083c96277549ee85623566b185810c\\\",\\\"style\\\":\\\"actionLine2\\\",\\\"marketingItemId\\\":\\\"MI5d3aa42b820144c78fdcdf18e14b25e9\\\"},\\\"expireTime\\\":1758472723149,\\\"marketingUniqueId\\\":\\\"MUc92881da752d4cf3a5dce4e0e7688bb1\\\",\\\"minClientVersion\\\":\\\"10.1.98\\\",\\\"recommendTemplateId\\\":\\\"actionLine2\\\",\\\"viewInfo\\\":{\\\"btnName\\\":\\\"支付奖励\\\",\\\"actionType\\\":\\\"link\\\",\\\"tagIcon\\\":\\\"https://mdn.alipayobjects.com/huamei_cke3ep/afts/img/A*s1xhTYe-_PQAAAAAAAAAAAAADk1-AQ/original\\\",\\\"tagColor\\\":\\\"#FF6011\\\",\\\"actionUrl\\\":\\\"alipays://platformapi/startapp?appId\u003d68687805\u0026url\u003dhttps%3A%2F%2Frender.alipay.com%2Fp%2Fyuyan%2F180020380000000023%2Fhome-page.html%3Fsource%3Ddzyyxiaoxi%26chInfo%3Ddzyyxiaoxi\\\",\\\"tag\\\":\\\"你有2561积分可使用\\\"}}}}\"}"}]
```

**Comment by AnkioTomas** [comment]
话说回来....这个issue是你自己复制提的吗？怎么那么诡异呢......
没用自动记账里面自带的反馈按钮？？
