### ISSUE TITLE
关于分类规则自定义编辑界面

### ISSUE THREAD

**Issue by mryuzhu** [AutoAccountingOrg/AutoAccounting#545]
### 描述建议

希望添加满足条件分类里面报销选项，目前分类只有类别希望可以添加是否报销。
![6ac78aef704f6b71877f87b547b9ea4](https://github.com/user-attachments/assets/ebb64680-c0c6-40d4-bbd3-05489b952451)

### 该功能带来的好处或者优点

```bash
优化使用体验感
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该功能尚未被报告。

**Comment by AnkioTomas** [comment]
不合理的需求，没有意义
