### ISSUE TITLE
自定义规则导致识别失败

### ISSUE THREAD

**Issue by mryuzhu** [AutoAccountingOrg/AutoAccounting#548]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

自定义规则导致识别失败

### 重现步骤

```bash
创建自定义规则，规则为如果....且....就分类....会导致，账本无法识别
```

### 相关环境说明

自动记账4.0.0-Canary.20240922061354
OS版本
Android 版本

1.0.10.0.UMNCNXM
14 UKQ1.230804.001
![d09de2545bd2c6a496e65ea44165939](https://github.com/user-attachments/assets/efb35822-53df-49b5-9ee8-7353759adaad)
![e48dd807be5839fa994a1eec518eb92](https://github.com/user-attachments/assets/12371ce8-1e56-4402-a785-1c79bddf1c4e)
![05de25f94b6398473ac3389c9441127](https://github.com/user-attachments/assets/6f46ed3e-6d8e-485e-954e-138fcb8c6920)
![8dcd7f2c068f9bdd9b305c3b9a0fa27](https://github.com/user-attachments/assets/d97d04ba-0f32-45e7-a539-cc0fbd40c04a)

### 日志内容

[log.txt](https://github.com/user-attachments/files/17089460/log.txt)

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
用最新的构建版试试https://github.com/AutoAccountingOrg/AutoAccounting/releases/tag/4.0.0-Canary.20240922154408

**Comment by mryuzhu** [comment]
问题复现，只要自定义规则包含“且”“金额范围”就会导致所有账单无法识别
[log.txt](https://github.com/user-attachments/files/17090415/log.txt)

**Comment by mryuzhu** [comment]
安装新版构建并且重启后，问题解决一般，可以识别规则了，但是识别结果并不可以按照，包含江西工业，且金额在2-15之间识别为三餐。
![Screenshot_2024-09-23-00-27-03-163_net ankio auto xposed](https://github.com/user-attachments/assets/8502ee28-7516-4bdc-8861-a4ac3169e3fc)
![Screenshot_2024-09-23-00-29-20-995_net ankio auto xposed](https://github.com/user-attachments/assets/70212cbb-7903-4bd7-91ad-4f2f990c3f6f)

[log.txt](https://github.com/user-attachments/files/17090424/log.txt)

**Comment by mryuzhu** [comment]
打错字了，是解决一半不是一般，不好意思不好意思。

**Comment by AnkioTomas** [comment]
正在构建中，一会删掉原来的规则重写：https://github.com/AutoAccountingOrg/AutoAccounting/actions/runs/10982722801

**Comment by mryuzhu** [comment]
好的作者大大别太晚睡，我先睡了明天早八，感谢大大付出，真的谢谢了

**Comment by AnkioTomas** [comment]
> 好的作者大大别太晚睡，我先睡了明天早八，感谢大大付出，真的谢谢了

年轻人就该熬夜~不然老了就熬不动了哈哈哈

**Comment by mryuzhu** [comment]
新版构建，问题已解决。
