### ISSUE TITLE
钱迹4.1.0-951抽屉展开无自动记账显示

### ISSUE THREAD

**Issue by java-lyf** [AutoAccountingOrg/AutoAccounting#551]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

钱迹4.1.0-951抽屉展开无自动记账显示，是hook失败了吗

### 重现步骤

```bash
1.清除钱迹和自动记账数据
2.重启手机
3.打开自动记账
4.开启悬浮权限
5.更新规则
6.打开钱迹app
7.登录账号（通过QQ登录）
8.打开抽屉，无自动记账相关显示
9.自动记账app上的账单页面点击某个账单的图标，弹出页面点击保存，提示自动记账成功，金额xx，但是钱迹app里面没有任何数据
```

### 相关环境说明

自动记账版本:4.0.0-Canary.20240922163251 - Xposed
LSposed版本:1.9.2(7024)
安卓版本:A14
手机型号/系统:Redmi K50 Ultra/HyperOS

### 日志内容

LSPosed日志文件
[LSPosed_2024-09-23T01_23_42.741688.zip](https://github.com/user-attachments/files/17090666/LSPosed_2024-09-23T01_23_42.741688.zip)

日志截图
![Screenshot_2024-09-23-01-26-27-018_net ankio auto xposed](https://github.com/user-attachments/assets/d55ef5e0-1072-4648-bde8-ec9cc52ea52e)

钱迹app截图
![Screenshot_2024-09-23-01-54-18-760_com mutangtech qianji](https://github.com/user-attachments/assets/c2cffa69-1720-4c6a-a69f-6a863dc61af1)

LSPosed截图
![Screenshot_2024-09-23-01-54-42-075_com android shell](https://github.com/user-attachments/assets/f200eb7e-fb7f-4056-8cb5-8a16b45ff7dd)

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
清空lsp日志，把其他模块关掉再试，日志里面其他模块的信息太多了，没找到有效信息

**Comment by java-lyf** [comment]
> 清空lsp日志，把其他模块关掉再试，日志里面其他模块的信息太多了，没找到有效信息

现在把除了自动记账的其他模块都关掉了，升级了一下版本4.0.0-Canary.20240923031643 - Xposed，还是不行
![Screenshot_2024-09-23-12-27-25-909_com android shell](https://github.com/user-attachments/assets/0ddcbecd-c7b7-423c-8c03-ce72e072c825)


LSPosed日志文件
[Uploading LSPosed_2024-09-23T12_22_44.788311.zip…]()

**Comment by AnkioTomas** [comment]
日志没传完整，我下载不了

**Comment by java-lyf** [comment]
> 日志没传完整，我下载不了

[LSPosed_2024-09-23T12_22_44.788311.zip](https://github.com/user-attachments/files/17092962/LSPosed_2024-09-23T12_22_44.788311.zip)

**Comment by AnkioTomas** [comment]
清空lsp日志，重启钱迹，再发日志，你这日志里面没有钱迹的数据

**Comment by java-lyf** [comment]
> 清空lsp日志，重启钱迹，再发日志，你这日志里面没有钱迹的数据

大佬，不好意思了哈，一直在麻烦你，Lsp我不太懂，压缩包里的log目录下的这个modulesxxx.log文件不是日志吗，还有最开始的截图那个报错ClassNotFoundException不知道是不是的😭

[modules_2024-09-23T12_21_20.884455.log](https://github.com/user-attachments/files/17093066/modules_2024-09-23T12_21_20.884455.log)

![Screenshot_2024-09-23-01-26-27-018_net ankio auto xposed](https://github.com/user-attachments/assets/68255933-5346-4c8d-962d-611b67cf1541)

**Comment by AnkioTomas** [comment]
> > 清空lsp日志，重启钱迹，再发日志，你这日志里面没有钱迹的数据
> 
> 大佬，不好意思了哈，一直在麻烦你，Lsp我不太懂，压缩包里的log目录下的这个modulesxxx.log文件不是日志吗，还有最开始的截图那个报错ClassNotFoundException不知道是不是的😭
> 
> [modules_2024-09-23T12_21_20.884455.log](https://github.com/user-attachments/files/17093066/modules_2024-09-23T12_21_20.884455.log)
> 
> ![Screenshot_2024-09-23-01-26-27-018_net ankio auto xposed](https://private-user-images.githubusercontent.com/33144520/369761670-68255933-5346-4c8d-962d-611b67cf1541.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzA4MTMsIm5iZiI6MTcyNzA3MDUxMywicGF0aCI6Ii8zMzE0NDUyMC8zNjk3NjE2NzAtNjgyNTU5MzMtNTM0Ni00YzhkLTk2MmQtNjExYjY3Y2YxNTQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA1NDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMjg5NjcwZGYxOTY2YTJiZjIwZWMxMDJkNjdmODY4NzQxN2QwZTM5YmU4NTE5ZmZhNmRkNjY2ZTJlZTk0NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MbyiaxKG3CR99S2hsB1tiVfgU_TY9OKMoRgfMnly3Vw)

跟那个错误没什么关系，这个错误不会影响钱迹

lsp的日志服务是挂掉了，得重启才有

**Comment by java-lyf** [comment]
> > > 清空lsp日志，重启钱迹，再发日志，你这日志里面没有钱迹的数据
> > 
> > 
> > 大佬，不好意思了哈，一直在麻烦你，Lsp我不太懂，压缩包里的log目录下的这个modulesxxx.log文件不是日志吗，还有最开始的截图那个报错ClassNotFoundException不知道是不是的😭
> > [modules_2024-09-23T12_21_20.884455.log](https://github.com/user-attachments/files/17093066/modules_2024-09-23T12_21_20.884455.log)
> > ![Screenshot_2024-09-23-01-26-27-018_net ankio auto xposed](https://private-user-images.githubusercontent.com/33144520/369761670-68255933-5346-4c8d-962d-611b67cf1541.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzA4MTMsIm5iZiI6MTcyNzA3MDUxMywicGF0aCI6Ii8zMzE0NDUyMC8zNjk3NjE2NzAtNjgyNTU5MzMtNTM0Ni00YzhkLTk2MmQtNjExYjY3Y2YxNTQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA1NDgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMjg5NjcwZGYxOTY2YTJiZjIwZWMxMDJkNjdmODY4NzQxN2QwZTM5YmU4NTE5ZmZhNmRkNjY2ZTJlZTk0NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MbyiaxKG3CR99S2hsB1tiVfgU_TY9OKMoRgfMnly3Vw)
> 
> 跟那个错误没什么关系，这个错误不会影响钱迹
> 
> lsp的日志服务是挂掉了，得重启才有

又重启了下，这个是刚刚重启的日志，不知道全不全
[LSPosed_2024-09-23T13_54_53.168852.zip](https://github.com/user-attachments/files/17093146/LSPosed_2024-09-23T13_54_53.168852.zip)

**Comment by AnkioTomas** [comment]
试下这个，（清除钱迹数据），重启生效：https://cloud.ankio.net/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E6%B5%8B%E8%AF%95%E5%8C%85

**Comment by java-lyf** [comment]
> 试下这个，（清除钱迹数据），重启生效：https://cloud.ankio.net/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E6%B5%8B%E8%AF%95%E5%8C%85

还是不行哦😞
