### ISSUE TITLE
规则开启自动记录功能后账单不同步钱迹

### ISSUE THREAD

**Issue by mryuzhu** [AutoAccountingOrg/AutoAccounting#557]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

无法自动同步账单

### 重现步骤

```bash
消费，自动记账记录账单
打开钱迹，无消费记录，
打开自动记账点击账单页面右上角刷新按钮
跳转钱迹，钱迹提示所有账单同步完成
重启手机，问题复现
依然无法同步
手动打开账单编辑界面
手动保存，
账单同步到钱迹
```

### 相关环境说明

自动记账4.0.0-Canary.20240923091333
OS版本
Android 版本

1.0.10.0.UMNCNXM
14 UKQ1.230804.001

![Screenshot_2024-09-23-18-28-05-236_net ankio auto xposed](https://github.com/user-attachments/assets/cf2b293c-fed0-40a0-8485-eabea0f81dc9)
![Screenshot_2024-09-23-18-13-17-985_com mutangtech qianji](https://github.com/user-attachments/assets/1c54871e-89f2-4daf-8db1-417769444ee5)

### 日志内容

[LSPosed_2024-09-23T18_30_05.098731.zip](https://github.com/user-attachments/files/17096174/LSPosed_2024-09-23T18_30_05.098731.zip)
[log.txt](https://github.com/user-attachments/files/17096182/log.txt)

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
确认一下记账方式，是否为不弹出编辑框记账（超时自动记录、点击悬浮窗自动记录）

**Comment by mryuzhu** [comment]
账单页面是有的付完款支付宝直接退回手机桌面了，因为是快捷键进入的付款码，全程没见到悬浮窗悬浮窗权限正常。
![Screenshot_2024-09-23-18-45-04-675_net ankio auto xposed](https://github.com/user-attachments/assets/2d78ec1c-80db-4d05-8ebf-c29e64f776de)

**Comment by AnkioTomas** [comment]
用最新版试下：https://github.com/AutoAccountingOrg/AutoAccounting/releases/tag/4.0.0-Canary.20240923091333

**Comment by mryuzhu** [comment]
![Screenshot_2024-09-23-19-06-16-729_net ankio auto xposed](https://github.com/user-attachments/assets/163cd607-1d3f-4c3e-86ba-2fb45a65f3e3)
![Screenshot_2024-09-23-19-06-11-457_com mutangtech qianji](https://github.com/user-attachments/assets/047c5c94-5743-43fd-b68b-81cdea27c208)
[log.txt](https://github.com/user-attachments/files/17096504/log.txt)
[LSPosed_2024-09-23T19_07_40.727999.zip](https://github.com/user-attachments/files/17096505/LSPosed_2024-09-23T19_07_40.727999.zip)
问题复现，全程没见到右边的悬浮窗

**Comment by AnkioTomas** [comment]
重启过了吗？日志好像不太对。
如果重启过了卸载重装一下（数据不会丢）

**Comment by mryuzhu** [comment]
![Screenshot_2024-09-23-19-33-08-687_com mutangtech qianji](https://github.com/user-attachments/assets/0cb230d6-43d4-4795-b591-399496d2a73c)
![Screenshot_2024-09-23-19-31-14-043_net ankio auto xposed](https://github.com/user-attachments/assets/7b59000a-8a2a-427a-93d6-01d9457c0ae6)
[LSPosed_2024-09-23T19_31_54.160580.zip](https://github.com/user-attachments/files/17096776/LSPosed_2024-09-23T19_31_54.160580.zip)
[log.txt](https://github.com/user-attachments/files/17096778/log.txt)
不好意思作者大大，刚刚确实忘记重启了，现在重启了，但是问题还是复现了

**Comment by AnkioTomas** [comment]
1. 卸载原来的版本
2. 安装：https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E6%B5%8B%E8%AF%95%E5%8C%85/app.apk
3. 重启
4. 打开自动记账的调试模式
5. 复现问题
6. 提供日志

**Comment by mryuzhu** [comment]
卸载原来的版本
安装：链接的版本
重启
打开软件
发现要重新在lsp打开模块
打开模块再重启
授予悬浮窗权限
更新规则
打开调试模式
付款0.01
未见付款后悬浮窗
打开自动记账
![Screenshot_2024-09-23-20-05-12-959_net ankio auto xposed](https://github.com/user-attachments/assets/235b0435-4abc-4bbb-846c-cb87fafba969)
账单-发现刚刚付款账单
打开钱迹
未见20：04：09的0.01订单最新订单为19：05手动点击账单保存的订单
![Screenshot_2024-09-23-20-07-55-931_com mutangtech qianji](https://github.com/user-attachments/assets/e9cd879e-bbc1-47f8-a5c8-4357a07ea910)
返回自动记账点击账单右上角刷新按钮，跳转钱迹
未见该账单
多任务界面关闭这两个软件
重复打开自动记账，点击刷新
小米提醒自动记账想打开钱迹
允许
钱迹被唤醒
仍然没有8：05账单
到此问题复现
刷新自动记账账单页面订单仍然同步标识显示未同步
![Screenshot_2024-09-23-20-12-27-142_net ankio auto xposed](https://github.com/user-attachments/assets/811d9fe8-9c6d-4867-8748-8d886a25e1ff)

开始保存日志-自动记账和lsposed日志

[log.txt](https://github.com/user-attachments/files/17097318/log.txt)

[LSPosed_2024-09-23T20_13_57.056496.zip](https://github.com/user-attachments/files/17097320/LSPosed_2024-09-23T20_13_57.056496.zip)
okok测试完毕加油作者大大，发布正式版，挂二维码，我请你喝柠檬水（手动滑稽）

**Comment by AnkioTomas** [comment]
找到问题了....你把支付宝消费设置为自动记录了.....所以没有弹窗.....至于同步问题是个bug

**Comment by mryuzhu** [comment]
好的大大，我的问题就主要是同步，自动记录我忘了，不好意思，大大加油。

**Comment by mryuzhu** [comment]
差不多确定了，那这个问题是不是该叫，自动记账在开启自动记账后，无法自动记账到钱迹。(˵¯͒〰¯͒˵)
![Screenshot_2024-09-23-21-19-40-156_net ankio auto xposed](https://github.com/user-attachments/assets/97a843c4-f959-4a7e-a3f6-9134f2bdc681)

**Comment by AnkioTomas** [comment]
`自动记录`功能

**Comment by mryuzhu** [comment]
安装最新版构建并且重启后
已解决这个问题
感谢作者大大
