### ISSUE TITLE
[Bug][Rule][DATA]com.tencent.mm

### ISSUE THREAD

**Issue by qewra99** [AutoAccountingOrg/AutoAccounting#562]
## 规则
{"mMap":{"tableName":"AppMessage","description":"交易时间：2024年9月24日 11:25:06\n交易类型：支出（尾号6272储蓄卡）\n交易金额：28.57（人民币）","source":"中国建设银行","arg":"msgId","type":5,"appId":"","msgId":480202,"title":"交易提醒"}}
## 说明
无交易对象内容，微信里有
## 数据
```
{"mMap":{"tableName":"AppMessage","description":"交易时间：2024年9月24日 11:25:06\n交易类型：支出（尾号6272储蓄卡）\n交易金额：28.57（人民币）","source":"中国建设银行","arg":"msgId","type":5,"appId":"","msgId":480202,"title":"交易提醒"}}
```

**Comment by AnkioTomas** [comment]
数据里没有
