### ISSUE TITLE
记账结果无法同步到钱迹

### ISSUE THREAD

**Issue by mynameiswutong** [AutoAccountingOrg/AutoAccounting#563]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

支付宝支付后弹窗记账成功，但是钱迹无账单

### 重现步骤

```bash
使用支付宝付款码支付
弹出弹窗点击保存，提示自动记账成功
手动打开钱迹查看无对应账单
自动记账app账单页面点击右上角刷新跳转到钱迹
卸载软件重新安装后重启问题复现
```

### 相关环境说明

自动记账：4.00-20240924030830
钱迹版本：4.1.0-951
手机版本：小米14Pro
OS版本：澎湃1.0.48.0UNBCNXM
安卓版本：14

### 日志内容

LSP截图
![Screenshot_2024-09-24-12-37-06-665_com android shell](https://github.com/user-attachments/assets/8058e461-fed7-4feb-8111-d2fcbf1c1ceb)
钱迹及自动记账截图
![Screenshot_2024-09-24-12-37-39-529_com mutangtech qianji](https://github.com/user-attachments/assets/b7a0e0b4-f267-4387-8f15-b7a5d15edfb2)
![Screenshot_2024-09-24-12-37-52-880_net ankio auto xposed](https://github.com/user-attachments/assets/826f9044-2a87-4b09-abaa-01c01efc1af0)
![Screenshot_2024-09-24-12-37-48-003_net ankio auto xposed](https://github.com/user-attachments/assets/d40daafd-9ea8-4db5-b622-1b4efa45c669)
![Screenshot_2024-09-24-12-37-41-464_com mutangtech qianji](https://github.com/user-attachments/assets/62ffce30-7972-48da-a6d2-1246191046a3)

LSP日志
[LSPosed_2024-09-24T12_36_19.359109.zip](https://github.com/user-attachments/files/17108171/LSPosed_2024-09-24T12_36_19.359109.zip)

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
重新编辑保存就可以同步了，我推测是因为记账的时候悬浮窗没有弹出来？

**Comment by mynameiswutong** [comment]
大佬，不好意思，不小心点到关闭了；
我试了下，重新编辑保存，还是没有数据（视频1）；另外我重新试了一次支付宝发红包，有弹窗但是钱迹里面仍然没有账单；并且发红包会弹出两个记账，一个是正常的支付，一个是错误的收入。
[Uploading ScreenRecorder.zip…]()

**Comment by mynameiswutong** [comment]
[ScreenRecorder.zip](https://github.com/user-attachments/files/17111850/ScreenRecorder.zip)

**Comment by AnkioTomas** [comment]
提供日志，或者更新最新的版本重启再试

**Comment by mynameiswutong** [comment]
用下午的最新版已经好了
