### ISSUE TITLE
自动记账自动同步功能

### ISSUE THREAD

**Issue by mryuzhu** [AutoAccountingOrg/AutoAccounting#565]
### 描述建议

在自动记账页面新添选项，可设置每多少分钟尝试自动同步账单到钱迹。
![IMG_20240924_162030](https://github.com/user-attachments/assets/10e6bf23-eec0-403a-ba4b-c502ac638951)

### 该功能带来的好处或者优点

```bash
提升用户体验感
多设备用户在使用钱迹时，使用非自动记账设备查看账单，可以省去手动同步功能，提高多设备账单同步性。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该功能尚未被报告。

**Comment by AnkioTomas** [comment]
定时同步这个方案研究了一下感觉不太行，会增加手机耗电
改为累计有5条/10条未同步的账单则打开钱迹进行同步

**Comment by AnkioTomas** [comment]
而且钱迹的同步需要拉起activity，手机如果是锁屏状态是无法拉起的

**Comment by mryuzhu** [comment]
好的好的大大，可以的，辛苦大大了。(◍•ᴗ•◍)✧*
