### ISSUE TITLE
改用url query的方式创建issue从而停止使用OAuth的方式自动创建issue

### ISSUE THREAD

**Issue by qwq233** [AutoAccountingOrg/AutoAccounting#597]
### 描述建议

根据GitHub的文档，创建issue时候可以通过添加title、body等参数以达到自动帮助用户创建issue。

E.G. `https://github.com/AutoAccountingOrg/AutoRule/issues/new?title=%5BAdaptation%20Request%5D%5BDATA%5Dcom.tencent.mm&body=%60%60%60%0A%7B%22mMap%22%3A%7B%22description%22%3A%22Paid%20by%20Balance%C2%A53900.00%5CnAcquirer%E8%B4%A2%E4%BB%98%E9%80%9A%E6%94%AF%E4%BB%98%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8%22%2C%22source%22%3A%22%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98%22%2C%22type%22%3A5%2C%22appId%22%3A%22%22%2C%22msgId%22%3A9964%2C%22title%22%3A%22%C2%A53900.00%20paid%22%2C%22display_name%22%3A%22%22%2C%22cachedPayTools%22%3A%22%E9%9B%B6%E9%92%B1%E9%80%9A%20%E4%B8%83%E6%97%A5%E5%B9%B4%E5%8C%961.64%25%22%2C%22cachedPayMoney%22%3A%22%EF%BF%A53900.00%22%2C%22cachedPayShop%22%3A%22%22%7D%7D%0A%60%60%60`

以下是上述例子的结果
![image](https://github.com/user-attachments/assets/f8953f9c-df38-4778-ad03-f40149153286)

reference: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/creating-an-issue

### 该功能带来的好处或者优点

目前通过OAuth授权来创建issue的方法可能带来安全性的隐患，OAuth授权将允许你/你们在任意仓库创建issue/pull request乃至和/或提交commit等危险操作。我并非不相信你们不会这么做，但是不排除你/你们由于某种原因泄露了你们的api key，导致不必要的风险。

该改动可有效避免这一缺陷，并允许用户手动填充更详细的信息，比如设备的语言等信息。

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该功能尚未被报告。

**Comment by AnkioTomas** [comment]
但是会有一些问题，Get请求的长度是有限制的，部分数据特别长的话，就没办法提交了

**Comment by qwq233** [comment]
或者你也可以请求用户提交自己的PAT (仅本地保存)，通过调用GitHub的API创建issue。
目前的方案显然不是很安全
至于GET请求长度上限我没找到官方的文档，我在Stacktrace Overflow看到有人说大概是8000 characters

**Comment by qwq233** [comment]
对于特别长的数据 也可以使用一些允许api调用的pastebin 我个人在用 fars.ee 算是对程序很友好了

**Comment by AnkioTomas** [comment]
pastebin 是个好主意，可以过期销毁~
