### ISSUE TITLE
微信适配失败

### ISSUE THREAD

**Issue by Mingyu2333** [AutoAccountingOrg/AutoAccounting#604]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

打开微信显示适配失败

### 重现步骤

```bash
更新到最新版，重启后打开微信适配失败
```

### 相关环境说明

自动记账：4.0.0-Canary.20240928151113 - Xposed
微信：8.0.51 国内版本
已在tg反馈，此次反馈提供为刚开机日志

### 日志内容

[3eb3cb24-12ea-4673-ba72-8a1e31712706.txt](https://github.com/user-attachments/files/17175379/3eb3cb24-12ea-4673-ba72-8a1e31712706.txt)
[LSPosed_2024-09-28T23_56_41.448811.zip](https://github.com/user-attachments/files/17175380/LSPosed_2024-09-28T23_56_41.448811.zip)
相关日志

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
腾讯热更新导致的问题：App Package Path: /data/user/0/com.tencent.mm/tinker/patch-a71b6d16/res/resources.apk

**Comment by AnkioTomas** [comment]
临时的解决方案是找到这个文件夹：patch-a71b6d16，然后删掉

**Comment by czxinshui** [comment]
自动记账：[4.0.0-Canary.20241031145928]
微信：8.0.53
系统miui14 微信一直卡死
