### ISSUE TITLE
[Bug][Rule][DATA]com.tencent.mm

### ISSUE THREAD

**Issue by ALin596** [AutoAccountingOrg/AutoAccounting#619]
![Uploading Screenshot_2024-10-02-23-53-20-921_net.ankio.auto.xposed.jpg…]()
## 规则
微信支付商家打款
## 说明
自动识别出来，没有时间信息，默认记录了1970年的初始日期，导致同步钱迹时显示参数失败
## 数据
[数据过期时间：2024-12-02 23:52:30](https://fars.ee/GIJw)

**Comment by AnkioTomas** [comment]
更新Github最新版
我记得已经修复了这个问题

—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by ALin596** [comment]
噢噢是的，我刚刚下载最新版测试，没有问题啦😊
