### ISSUE TITLE
无法获取微信数据

### ISSUE THREAD

**Issue by Mingyu2333** [AutoAccountingOrg/AutoAccounting#628]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

无法获取微信数据，包括普通支付与服务消息等，所有数据

### 重现步骤

```bash
使用微信支付，无法弹出自动记账，查看日志及数据没有相关内容。
```

### 相关环境说明

4.0.0-Canary.20241001030800
微信8.0.51

### 日志内容

支付时间：11:56
日志截止至12点
[log(5).txt](https://github.com/user-attachments/files/17265172/log.5.txt)
[LSPosed_2024-10-05T12_01_18.634046.zip](https://github.com/user-attachments/files/17265173/LSPosed_2024-10-05T12_01_18.634046.zip)

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
先清空lsp和自动记账的日志，手机重启再支付发日志，lsp日志崩了~那个时间的日志没得了

**Comment by Mingyu2333** [comment]
> 先清空lsp和自动记账的日志，手机重启再支付发日志，lsp日志崩了~那个时间的日志没得了

 付款时间：17:48:40
[LSPosed_2024-10-05T17_49_44.211494.zip](https://github.com/user-attachments/files/17265756/LSPosed_2024-10-05T17_49_44.211494.zip)
[log(3)(1).txt](https://github.com/user-attachments/files/17265758/log.3.1.txt)
