### ISSUE TITLE
[Bug][Rule][DATA]com.tencent.mm

### ISSUE THREAD

**Issue by LanFeng11** [AutoAccountingOrg/AutoAccounting#634]
## 规则
微信公众号美团
## 说明
美团月付还款通知
## 数据
[数据过期时间：2024-12-08 16:06:13](https://fars.ee/EjqS)

**Comment by AnkioTomas** [comment]
这个不是规则问题，数据里面压根没有明显的特征可以区分是还款还是纯粹的微信支付

**Comment by LanFeng11** [comment]
哦哦，确实是这样
