### ISSUE TITLE
自动记账同步不了钱迹

### ISSUE THREAD

**Issue by kk0121** [AutoAccountingOrg/AutoAccounting#662]
### 问题

自动记账不能同步钱迹 钱迹跟自动记账都是最新版本 lsp也勾选了   进钱迹app还是识别不出模块
[详细日志.zip](https://github.com/user-attachments/files/17390077/default.zip)
[模块日志.zip](https://github.com/user-attachments/files/17390081/default.zip)

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该问题尚未被报告。

**Comment by Dr-Roy-Zhao** [comment]
好像跟我的一样，但是我的会显示同步成功，然而钱迹没有任何数据。
