### ISSUE TITLE
钱迹无法同步，不显示插件

### ISSUE THREAD

**Issue by Dr-Roy-Zhao** [AutoAccountingOrg/AutoAccounting#669]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 梦境
- [ ] 其他虚拟框架
- [ ] 轮回

### 描述错误

自动记账账单有数据，但是点同步会显示成功，然后钱迹没有任何变化，自动记账的同步按钮出现斜杠

### 重现步骤

```bash
自动记账账单有数据，但是点同步会显示成功，然后钱迹没有任何变化，自动记账的同步按钮出现斜杠。
已自检相关问题，LSP中勾选，重启，更换版本都已经做了。
```

### 相关环境说明

自动记账版本 4.0.0-Canary、20241019121906
钱迹版本4.1.0-951
安卓版本 14（HyperOS 1.0.8.0.ULTCNXM）
LSP版本 github原版 1.10.1（7115）

### 日志内容

[
[LSPosed_2024-10-19T22_55_50.533964.zip](https://github.com/user-attachments/files/17445780/LSPosed_2024-10-19T22_55_50.533964.zip)
](url)

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
lsp地址给我一下，最新官方版不是才到1.9.2就停更了吗

**Comment by AnkioTomas** [comment]
或者使用这个版本，配合Zygisk-Next,https://github.com/re-zero001/LSPosed-Irena

**Comment by Dr-Roy-Zhao** [comment]
https://github.com/JingMatrix/LSPosed/releases



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月20日 11:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AutoAccountingOrg/AutoAccounting] 钱迹无法同步，不显示插件 (Issue #669) |

lsp地址给我一下，最新官方版不是才到1.9.2就停更了吗

**Comment by AnkioTomas** [comment]
不要用这个版本，问题太多

**Comment by AnkioTomas** [comment]
这才是官方原版：https://github.com/LSPosed/LSPosed

**Comment by Dr-Roy-Zhao** [comment]
好的，我尽快试试

**Comment by Dr-Roy-Zhao** [comment]
已经更过了这个版本，仍然不生效，lsp日志已上传








---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月20日 11:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AutoAccountingOrg/AutoAccounting] 钱迹无法同步，不显示插件 (Issue #669) |

或者使用这个版本，配合Zygisk-Next,https://github.com/re-zero001/LSPosed-Irena

**Comment by Dr-Roy-Zhao** [comment]
[LSPosed_2024-10-20T12_12_00.362226.zip](https://github.com/user-attachments/files/17448885/LSPosed_2024-10-20T12_12_00.362226.zip)
![微信图片_20241020121620](https://github.com/user-attachments/assets/ffae2613-ccd8-40b2-a8df-ac5bf151594a)
![微信图片_20241020121605](https://github.com/user-attachments/assets/e8f47f5e-5e81-4885-9db4-2f3a08fd9ced)
![微信图片_20241020121556](https://github.com/user-attachments/assets/e2b0e813-f043-4f7d-bff4-b37767011ace)

**Comment by Dr-Roy-Zhao** [comment]
LSP的原版也1.9.2（7024）也试过了，没有生效，目前钱迹里面左边页面最下面不显示自动记账插件

**Comment by AnkioTomas** [comment]
使用这个版本的钱迹也不行吗（卸载重装）？https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E9%92%B1%E8%BF%B9/qianji_410_951_gw.apk

**Comment by AnkioTomas** [comment]
初步判断是这个位置（https://github.com/AutoAccountingOrg/AutoAccounting/blob/master/app/src/xposed/java/net/ankio/auto/core/App.kt#L260C12-L265C14）的hook出了问题，难道入口不一样？
你把你的钱迹打个包发上来

**Comment by Dr-Roy-Zhao** [comment]
> 使用这个版本的钱迹也不行吗（卸载重装）？https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E9%92%B1%E8%BF%B9/qianji_410_951_gw.apk

我用的就是这个版本的钱迹，从您的网盘里下载的，我今天重装了3次，哈哈哈

**Comment by AnkioTomas** [comment]
> > 使用这个版本的钱迹也不行吗（卸载重装）？https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E9%92%B1%E8%BF%B9/qianji_410_951_gw.apk
> 
> 我用的就是这个版本的钱迹，从您的网盘里下载的，我今天重装了3次，哈哈哈

这就很离谱了，我们现在的环境一模一样....除了我是vip以外.....
我明天有空的话单独发一个版本你试一下

**Comment by Dr-Roy-Zhao** [comment]
感谢大佬

**Comment by AnkioTomas** [comment]
试试这个https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E6%B5%8B%E8%AF%95/app.apk

**Comment by Dr-Roy-Zhao** [comment]
> 试试这个https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E6%B5%8B%E8%AF%95/app.apk

已经进行了替换，重启，停用其他模块等操作，目前钱迹里面左边页面最下面不显示自动记账插件，但LSP其他模块的正常工作，感觉没有
[LSPosed_2024-10-20T22_19_32.591099.zip](https://github.com/user-attachments/files/17450632/LSPosed_2024-10-20T22_19_32.591099.zip)
hook钱迹，日志已发

**Comment by AnkioTomas** [comment]
> > 试试这个https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E6%B5%8B%E8%AF%95/app.apk
> 
> 已经进行了替换，重启，停用其他模块等操作，目前钱迹里面左边页面最下面不显示自动记账插件，但LSP其他模块的正常工作，感觉没有 [LSPosed_2024-10-20T22_19_32.591099.zip](https://github.com/user-attachments/files/17450632/LSPosed_2024-10-20T22_19_32.591099.zip) hook钱迹，日志已发

按物理键重启手机，再发日志，日志挂了

**Comment by Dr-Roy-Zhao** [comment]
> > > 试试这个https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E6%B5%8B%E8%AF%95/app.apk
> > 
> > 
> > 已经进行了替换，重启，停用其他模块等操作，目前钱迹里面左边页面最下面不显示自动记账插件，但LSP其他模块的正常工作，感觉没有 [LSPosed_2024-10-20T22_19_32.591099.zip](https://github.com/user-attachments/files/17450632/LSPosed_2024-10-20T22_19_32.591099.zip) hook钱迹，日志已发
> 
> 按物理键重启手机，再发日志，日志挂了

[LSPosed_2024-10-21T09_30_13.226406.zip](https://github.com/user-attachments/files/17452980/LSPosed_2024-10-21T09_30_13.226406.zip)

**Comment by AnkioTomas** [comment]
> > > > 试试这个https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E6%B5%8B%E8%AF%95/app.apk
> > > 
> > > 
> > > 已经进行了替换，重启，停用其他模块等操作，目前钱迹里面左边页面最下面不显示自动记账插件，但LSP其他模块的正常工作，感觉没有 [LSPosed_2024-10-20T22_19_32.591099.zip](https://github.com/user-attachments/files/17450632/LSPosed_2024-10-20T22_19_32.591099.zip) hook钱迹，日志已发
> > 
> > 
> > 按物理键重启手机，再发日志，日志挂了
> 
> [LSPosed_2024-10-21T09_30_13.226406.zip](https://github.com/user-attachments/files/17452980/LSPosed_2024-10-21T09_30_13.226406.zip)

你确定你是按物理键重启的吗？
![image](https://github.com/user-attachments/assets/6274e527-562a-40f5-af33-4001d5e592b0)

**Comment by Dr-Roy-Zhao** [comment]
> > > > > 试试这个https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E6%B5%8B%E8%AF%95/app.apk
> > > > 
> > > > 
> > > > 已经进行了替换，重启，停用其他模块等操作，目前钱迹里面左边页面最下面不显示自动记账插件，但LSP其他模块的正常工作，感觉没有 [LSPosed_2024-10-20T22_19_32.591099.zip](https://github.com/user-attachments/files/17450632/LSPosed_2024-10-20T22_19_32.591099.zip) hook钱迹，日志已发
> > > 
> > > 
> > > 按物理键重启手机，再发日志，日志挂了
> > 
> > 
> > [LSPosed_2024-10-21T09_30_13.226406.zip](https://github.com/user-attachments/files/17452980/LSPosed_2024-10-21T09_30_13.226406.zip)
> 
> 你确定你是按物理键重启的吗？ ![image](https://private-user-images.githubusercontent.com/155616939/378246900-6274e527-562a-40f5-af33-4001d5e592b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NzcwMzUsIm5iZiI6MTcyOTQ3NjczNSwicGF0aCI6Ii8xNTU2MTY5MzkvMzc4MjQ2OTAwLTYyNzRlNTI3LTU2MmEtNDBmNS1hZjMzLTQwMDFkNWU1OTJiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQwMjEyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZThlMjE0MzQ0YmM1MjFlMzYxODc0Y2EwYmM2MzRjNjM3OTM3MzgwNDYyYTNkZTA3MDA4MGM1NmYyNzZlMWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K2lqoGZFbGQkQaEEZH49Yr7Qe5v5XOeeL9pDFUGxu6s)
直接长按关机键，3秒之后才会弹出重启，然后点重启，我这次长按7秒直接来的
[LSPosed_2024-10-21T10_15_27.475508.zip](https://github.com/user-attachments/files/17453203/LSPosed_2024-10-21T10_15_27.475508.zip)

**Comment by AnkioTomas** [comment]
日志没上传完成

**Comment by Dr-Roy-Zhao** [comment]
[LSPosed_2024-10-21T10_15_27.475508.zip](https://github.com/user-attachments/files/17453350/LSPosed_2024-10-21T10_15_27.475508.zip)

**Comment by AnkioTomas** [comment]
清空lsp日志，用这个（https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E6%B5%8B%E8%AF%95/app2.apk），lsp里面只勾选钱迹，重启钱迹，然后发我日志

**Comment by Dr-Roy-Zhao** [comment]
> 清空lsp日志，用这个（[https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E6%B5%8B%E8%AF%95/app2.apk），lsp里面只勾选钱迹，重启钱迹，然后发我日志](https://cloud.ankio.net/d/%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6/%E6%B5%8B%E8%AF%95/app2.apk%EF%BC%89%EF%BC%8Clsp%E9%87%8C%E9%9D%A2%E5%8F%AA%E5%8B%BE%E9%80%89%E9%92%B1%E8%BF%B9%EF%BC%8C%E9%87%8D%E5%90%AF%E9%92%B1%E8%BF%B9%EF%BC%8C%E7%84%B6%E5%90%8E%E5%8F%91%E6%88%91%E6%97%A5%E5%BF%97)

APP下载失败......

**Comment by AnkioTomas** [comment]
https://1drv.ms/u/s!Akg4xr_s219pga4uvW7XOOz4J595DA?e=Ghtypl

**Comment by Dr-Roy-Zhao** [comment]
> https://1drv.ms/u/s!Akg4xr_s219pga4uvW7XOOz4J595DA?e=Ghtypl

[LSPosed_2024-10-21T12_08_30.272868.zip](https://github.com/user-attachments/files/17454883/LSPosed_2024-10-21T12_08_30.272868.zip)

**Comment by AnkioTomas** [comment]
自动记账完全没有作用到钱迹嘛....

**Comment by AnkioTomas** [comment]
方便的话给我todesk连接，我远程看一下：ankio@ankio.net

**Comment by Dr-Roy-Zhao** [comment]
> 自动记账完全没有作用到钱迹嘛....

是这个感觉，酷安也有跟我同样问题的朋友。钱迹设置下面完全没有自动记账的标志，而且，自动记账能读取钱迹的信息，能看到有什么账户，但是写入不了，自动记账每次都显示成功同步，但是钱迹没有任何反应。

**Comment by Dr-Roy-Zhao** [comment]
> 方便的话给我todesk连接，我远程看一下：[ankio@ankio.net](mailto:ankio@ankio.net)
单位的网络，屏蔽TODESK、向日葵一类的软件了，抱歉

**Comment by AnkioTomas** [comment]
那晚一点的话用自己的设备看一下吧
这个问题很诡异

开maigk隐藏列表了么

日志显示lsp已经注入自动记账到钱迹了
但是自动记账的注入代码根本没有输出log
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by Dr-Roy-Zhao** [comment]
> 那晚一点的话用自己的设备看一下吧 这个问题很诡异 开maigk隐藏列表了么 日志显示lsp已经注入自动记账到钱迹了 但是自动记账的注入代码根本没有输出log ————————— Ankio 敬上 ***@***.*** 若无闲事挂心头，便是人间好时节。

开了，但是没有把自动记账和钱迹放进去。
方便问一下您用的哪个版本的magisk么？

**Comment by AnkioTomas** [comment]
我用的是alpha版的magisk

—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by AnkioTomas** [comment]
试下这个版本的钱迹：https://app.qianjiapp.com/qianji_411b6_958_beta.apk

**Comment by Dr-Roy-Zhao** [comment]
可以了！！！！！感谢大佬，如果可以的话，请提供捐赠地址！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月23日 14:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [AutoAccountingOrg/AutoAccounting] 钱迹无法同步，不显示插件 (Issue #669) |

试下这个版本的钱迹：https://app.qianjiapp.com/qianji_411b6_958_beta.apk

**Comment by AnkioTomas** [comment]
好诡异的bug。容我再研究研究，不合理~~~
捐赠的话，爱发电：https://afdian.com/a/ankio/plan
