### ISSUE TITLE
关于钱迹

### ISSUE THREAD

**Issue by ClarkQAQ** [AutoAccountingOrg/AutoAccounting#678]
### 描述建议

能不能脱离钱迹, 哪怕只是把记录写入一个文件 (CSV 甚至纯文本), 或者软件自己的数据库, 然后由用户自己去想办法处理...

### 该功能带来的好处或者优点

```bash
因为钱迹太恶心了, 做什么都得登录, 哪怕那些功能明明就是本地功能, 而且不是自由软件...
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该功能尚未被报告。

**Comment by AnkioTomas** [comment]
自动记账的账单是写在自己的数据库的。

钱迹通过API的方式调用自动记账的数据库实现账单记录。

换言之，如果有这样的第三方App来调用自动记账的数据库接口，也是可以和钱迹一样实现自动记账的。
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by ClarkQAQ** [comment]
> 自动记账的账单是写在自己的数据库的。 钱迹通过API的方式调用自动记账的数据库实现账单记录。 换言之，如果有这样的第三方App来调用自动记账的数据库接口，也是可以和钱迹一样实现自动记账的。 ————————— Ankio 敬上 ***@***.*** 若无闲事挂心头，便是人间好时节。

但是目前没安装钱迹的话每次切换到主页都会弹窗口让安装钱迹, 并且因为没法创建资产也没法正常记账...

**Comment by ClarkQAQ** [comment]
我知道了...关掉 [资产管理功能] 就可以了...

**Comment by AnkioTomas** [comment]
因为自动记账并不是一个记账软件，它没有专业记账软件的功能，他只是一个账单获取、整合的工具
所以需要一个记账软件来配合使用。

对于资产的问题，可以禁用资产管理。
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。
