### ISSUE TITLE
微信红包来源识别错误

### ISSUE THREAD

**Issue by Adlyq** [AutoAccountingOrg/AutoAccounting#693]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

如题

### 重现步骤

```bash
收到红包
查看原始数据
hookeruser的值和实际的对不上，总是显示为某个公众号
```

### 相关环境说明

自动记账 4.0.0-Canary.20241021032044
微信 8049

### 日志内容

无

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
如果可以的话，建议更新微信8053

**Comment by Adlyq** [comment]
emmm，vx模块好久没更新了，不适配较新的微信版本

**Comment by AnkioTomas** [comment]
> emmm，vx模块好久没更新了，不适配较新的微信版本

那等我有空研究研究

**Comment by AnkioTomas** [comment]
试下最新的构建版
