### ISSUE TITLE
微信8049，发送红包以及转账不会记账

### ISSUE THREAD

**Issue by smpanand** [AutoAccountingOrg/AutoAccounting#695]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

微信8049，发送红包以及转账无法自动记账

### 重现步骤

```bash
微信8049，发送红包以及转账无法自动记账
```

### 相关环境说明

自动记账:141500
lsp:7232
安卓版本13

### 日志内容

无

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by smpanand** [comment]
因为vx停更的缘故，故无法更新至49后续版本

**Comment by AnkioTomas** [comment]
如果有数据的话可以上传数据看看，没数据的话开调试模式，看看日志里面有没有相关的数据

**Comment by smpanand** [comment]
> 如果有数据的话可以上传数据看看，没数据的话开调试模式，看看日志里面有没有相关的数据

{"content":{"mMap":{"tableName":"message","msgSvrId":7952858980258551183,"isSend":0,"msgSeq":825328676,"status":4,"talker":"wxid_tfr1ivgfc30t22","talkerId":9723,"lvbuffer":[123,0,0,0,0,0,0,0,118,60,109,115,103,115,111,117,114,99,101,62,10,9,60,115,105,103,110,97,116,117,114,101,62,118,49,95,47,73,99,48,78,99,77,68,60,47,115,105,103,110,97,116,117,114,101,62,10,9,60,116,109,112,95,110,111,100,101,62,10,9,9,60,112,117,98,108,105,115,104,101,114,45,105,100,62,60,47,112,117,98,108,105,115,104,101,114,45,105,100,62,10,9,60,47,116,109,112,95,110,111,100,101,62,10,60,47,109,115,103,115,111,117,114,99,101,62,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,125],"t":1729957526265,"arg":"msgId","flag":0,"type":10000,"msgId":10225322,"bizChatId":-1,"content":"<img src=\"SystemMessages_HongbaoIcon.png\"/>  小高领取了你的<_wc_custom_link_ color=\"#FD9931\" href=\"weixin://weixinhongbao/opendetail?sendid=1000039801202410267119484471025\">红包</_wc_custom_link_>","bizClientMsgId":"","createTime":1729957525000}},"hookerUser":"潘翔","cachedPayTools":"零钱","cachedPayMoney":"￥0.01","cachedPayShop":"微信红包","t":1729957526274}

**Comment by AnkioTomas** [comment]
显然，hook没有任何问题，只是缺少规则而已，所以这不是bug

**Comment by smpanand** [comment]
> 显然，hook没有任何问题，只是缺少规则而已，所以这不是bug

转账的日志需要怎么发送呢，转账没有数据

**Comment by AnkioTomas** [comment]
你可以点开你那个转账信息试试？
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by smpanand** [comment]
> 你可以点开你那个转账信息试试？
> —————————
> Ankio 敬上
> ***@***.***
> 若无闲事挂心头，便是人间好时节。
> 
> 

原来如此，必须要点开转账才能被命中

**Comment by smpanand** [comment]
> 显然，hook没有任何问题，只是缺少规则而已，所以这不是bug

那红包收款也是因为没有规则吧
{"content":{"mMap":{"tableName":"message","isSend":0,"status":3,"talker":"wxid_tfr1ivgfc30t22","talkerId":9723,"t":1729959713912,"arg":"msgId","type":10000,"msgId":10225424,"bizChatId":-1,"content":"<img src=\"SystemMessages_HongbaoIcon.png\"/>  你领取了高思瑜的<_wc_custom_link_ color=\"#FD9931\" href=\"weixin://weixinhongbao/opendetail?sendid=1000039801202410276094535770044&sign=a6cd9707a2f2399b39271bceebc70deccaa5be8e1573f3de6ecc9a0db3b73f04300c8a3a382996425d2bba40d49eba76f8e0c04efeddf722aa8f4d918fb5ebad74af83a07c33f13d59c354f97aebf806&ver=6\">红包</_wc_custom_link_>","createTime":1729959713000}},"hookerUser":"潘翔","cachedPayTools":"零钱","cachedPayMoney":"￥0.01","cachedPayShop":"向高思瑜(**瑜)转账","t":1729959713914}
