### ISSUE TITLE
[Bug][Rule][DATA]com.tencent.mm

### ISSUE THREAD

**Issue by MeepoMaster** [AutoAccountingOrg/AutoAccounting#709]
![Screenshot_2024-10-29-13-16-29-249_net ankio auto xposed](https://github.com/user-attachments/assets/87471dee-b7fc-4238-82aa-84eae0ebeb3f)
## 规则
微信公众号中国建设银行
## 说明
微信公众号，建行信用卡支付后，记账时间默认为1970-01-01早上8点
## 数据
[数据过期时间：2024-12-29 13:18:08](https://fars.ee/Z-ps)

**Comment by AnkioTomas** [comment]
规则没有问题，更新自动记账
