### ISSUE TITLE
锁屏发生交易的通知栏提醒方案

### ISSUE THREAD

**Issue by TrioTea** [AutoAccountingOrg/AutoAccounting#740]
### 描述建议

检测到锁屏状态下的交易时，立即发送一条通知
通知内容包含交易金额、商家等关键信息
通知持久化显示，不会自动消失
点击通知后，弹出悬浮窗进行记账

### 该功能带来的好处或者优点

```bash
不影响系统安全性，用户体验自然
不hook系统UI，减少不同系统之间的兼容性问题
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该功能尚未被报告。

**Comment by AnkioTomas** [comment]
没有hook系统UI，在短信里面添加解锁监听广播：https://github.com/AutoAccountingOrg/AutoAccounting/commit/8c8686f18cda501cc5660801d15d78a46a5b9b0f

下个自动构建版本将包含该功能
