### ISSUE TITLE
大模型返回结果错误

### ISSUE THREAD

**Issue by zfqit** [AutoAccountingOrg/AutoAccounting#748]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

大模型返回结果错误

### 重现步骤

```bash
使用该项目获取免费 openai API KEY 和公共访问地址
项目地址: https://github.com/popjane/free_chatgpt_api
```

### 相关环境说明

自动记账版本:  24241031145928 安卓版本 13 钱迹版本4.1.0-951
![微信图片_20241116211817](https://github.com/user-attachments/assets/c8606968-5760-4a6f-a2dc-e570e7ca1c66)

### 日志内容

错误报错
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
接口地址没写全吧，域名后面加上下面的试试

/v1/chat/completions
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by zfqit** [comment]
> 接口地址没写全吧，域名后面加上下面的试试 /v1/chat/completions ————————— Ankio 敬上 ***@***.*** 若无闲事挂心头，便是人间好时节。

/v1/chat/completions
加上完毕后的地址为: https://free.v36.cm/v1/chat/completions
报错原因如下:
![微信图片_20241116211817](https://github.com/user-attachments/assets/5453e3ee-ac03-4699-a3e0-a335010c4537)

**Comment by AnkioTomas** [comment]
没问题了，不是错误，单纯是因为这个大模型没有识别到数据。

—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by zfqit** [comment]
ok, 感想
