### ISSUE TITLE
多项数据删除无效

### ISSUE THREAD

**Issue by TrioTea** [AutoAccountingOrg/AutoAccounting#767]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

多项数据删除无效

### 重现步骤

```bash
- 自定义分类规则中的分类数据删除无效
- 账单右上角删除无效
```

### 相关环境说明

自动记账-[4.0.0-Canary.20241121032305](https://github.com/AutoAccountingOrg/AutoAccounting/releases/tag/4.0.0-Canary.20241121032305)
LSP-尝试v1.9.2-7274
安卓信息-小米澎湃OS2.0.6.3【安卓15】

### 日志内容

[log-账单.txt](https://github.com/user-attachments/files/17856420/log-.txt)
[log-分类数据.txt](https://github.com/user-attachments/files/17856423/log-.txt)

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
好像还有一些编辑也有错误，也无法编辑

**Comment by TrioTea** [comment]
> 好像还有一些编辑也有错误，也无法编辑

咦，这个我暂时还没遇到，我编辑得比较少

**Comment by TrioTea** [comment]
> 好像还有一些编辑也有错误，也无法编辑

早上好，我想请问下，🥹怎么把自动记账现有的账单数据等等清除啊，卸载重装也不管用，是不是数据在“电话”里

**Comment by AnkioTomas** [comment]
com.android.phone
databases目录下autoAccounting.db 
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by TrioTea** [comment]
> com.android.phone
> databases目录下autoAccounting.db 
> —————————
> Ankio 敬上
> ***@***.***
> 若无闲事挂心头，便是人间好时节。
> 
> 

感谢回复，搞定了☺️
另外请问一下，自动记账的规则有无较大的变更机会，也可以提 pr 贡献吧

**Comment by AnkioTomas** [comment]
> > com.android.phone
> > databases目录下autoAccounting.db
> > —————————
> > Ankio 敬上
> > _**@**_.***
> > 若无闲事挂心头，便是人间好时节。
> 
> 感谢回复，搞定了☺️ 另外请问一下，自动记账的规则有无较大的变更机会，也可以提 pr 贡献吧

想做一些什么样的变更呢？如果变更可以让现在的规则编写方式和使用方式更简便，同时对用户来讲又不需要做太大的变更的话，自然是欢迎PR的

**Comment by TrioTea** [comment]
我周末可能会适配一部分数据的匹配，逻辑上的变更，一些想法暂时还需要验证🫡

Ankio ***@***.***> 于 2024年11月23日周六 下午12:45写道：
