### ISSUE TITLE
[Feature] 支持自动备份

### ISSUE THREAD

**Issue by PoeraWork** [AutoAccountingOrg/AutoAccounting#768]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

更新最新测试版后数据库丢失内容

### 重现步骤

```bash
1.升级到4.0.0-Canary.20241121032305后所有账单与规则丢失(之前的版本应该是4.0.0-Canary.20241031145928)
2.备份后卸载重装自动记账，从备份恢复后规则仍是空的，查看备份文件可以发现数据库大小不对。
```

### 相关环境说明

4.0.0-Canary.20241121032305

### 日志内容

<img src="https://github.com/user-attachments/assets/8dff14d7-00d1-421a-a45e-c8cb68d9d169" width="200px">
<img src="https://github.com/user-attachments/assets/cfdb8dbf-a9e4-4071-ae1d-e22b78f2efc8" width="200px">
<img src="https://github.com/user-attachments/assets/418a0944-0a8f-44cd-b0bd-46582bc08837" width="500px">

## 问题和建议
安装前我忘了备份，丢数据倒不影响，不过能否添加一个按键用于**重装规则**，不然没法识别。我最后是从上个月的备份恢复才能用的。
另外后续是否有应用内更新的计划，到时候加个更新前备份就安全了。

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
重装规则长按首页的规则更新按钮。
应用内更新计划暂时没有，不过可以考虑实现自动备份

**Comment by PoeraWork** [comment]
欸？长按我试过了啊，没用

**Comment by AnkioTomas** [comment]
你按的哪儿
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by PoeraWork** [comment]
> 你按的哪儿 ————————— Ankio 敬上 ***@***.*** 若无闲事挂心头，便是人间好时节。

记账规则旁的那个转圈按钮
![81f379747fce23a86df0cf9a86c347c4](https://github.com/user-attachments/assets/fc5399b1-c090-48a0-ae0b-5ad3d9b79dac)

**Comment by AnkioTomas** [comment]
网络问题导致的吧

**Comment by PoeraWork** [comment]
> 网络问题导致的吧

确实，刚开科学试了下可以了。我这github基本能裸连，就没往这方面想。辛苦大佬了，期待正式版！
