### ISSUE TITLE
微信总是掉后台，看日志出现错误

### ISSUE THREAD

**Issue by shenymo** [AutoAccountingOrg/AutoAccounting#781]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

微信掉后台

### 重现步骤

```bash
1.最开始使用的时候，出现过掉后台的情况，且自动记账里面有错误日志，之后在LSPosed里面重新优化了一下微信，稳定使用了这几天
2.从昨天开始又出现掉后台的情况，重新优化也没有作用了。
```

### 相关环境说明

自动记账版本：4.0.0-Canary.20241121032305
微信版本：8.0.54
钱迹版本：4.1.0
系统版本：安卓14 Flyme 11.24.11.19 daily

### 日志内容

2024-11-27 13:38:30  HookerEnvironment  [INFO][App]InitHooker: 微信, AutoVersion: 4.0.0-Canary.20241121032305 - Xposed, Application: /data/app/~~ry4mFQxm9GxKYO9fgbRXZA==/com.tencent.mm-L2SwpNRLDhOqk-hSLxgTdA==/base.apk
2024-11-27 13:38:30  com.tencent.mm  [INFO][WechatHooker]tinkerDir: /data/user/0/com.tencent.mm/tinker
2024-11-27 13:38:30  com.tencent.mm  [ERROR][App]java.lang.ClassNotFoundException: com.tencent.tinker.lib.tinker.TinkerApplicationHelper
de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:12)
net.ankio.auto.xposed.hooks.wechat.WechatHooker.closeTinker(WechatHooker.kt:221)
net.ankio.auto.xposed.hooks.wechat.WechatHooker.hookLoadPackage(WechatHooker.kt:69)
net.ankio.auto.xposed.core.App.initHooker(App.kt:267)
net.ankio.auto.xposed.core.App.access$initHooker(App.kt:54)
net.ankio.auto.xposed.core.App$handleLoadPackage$1.invoke(App.kt:135)
net.ankio.auto.xposed.core.App$handleLoadPackage$1.invoke(App.kt:134)
net.ankio.auto.xposed.core.App.hookAppContext$onCachedApplication(App.kt:90)
net.ankio.auto.xposed.core.App.access$hookAppContext$onCachedApplication(App.kt:54)
net.ankio.auto.xposed.core.App$hookAppContext$hookApplication$1.invoke(App.kt:106)
net.ankio.auto.xposed.core.App$hookAppContext$hookApplication$1.invoke(App.kt:100)
net.ankio.auto.xposed.core.hook.Hooker$after$1.afterHookedMethod(Hooker.kt:103)
de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
J.callback(Unknown Source:292)
LSPHooker_.attachBaseContext(Unknown Source:11)
com.tencent.mm.app.Application.attachBaseContext(Unknown Source:0)
android.app.Application.attach(Application.java:346)
android.app.Instrumentation.newApplication(Instrumentation.java:1288)
android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1404)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:7150)
android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2280)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loopOnce(Looper.java:205)
android.os.Looper.loop(Looper.java:294)
android.app.ActivityThread.main(ActivityThread.java:8417)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)

2024-11-27 13:38:30  HookerEnvironment  [INFO][App]App VersionCode: 2760, VersionName: 8.0.54
2024-11-27 13:38:30  com.tencent.mm  [INFO][App]Adaptation Info:{remittance.model=com.tencent.mm.plugin.remittance.model.g1, luckymoney.model=com.tencent.mm.plugin.luckymoney.model.n5}
2024-11-27 13:25:05  HookerEnvironment  [INFO][App]App VersionCode: 2760, VersionName: 8.0.54
2024-11-27 13:25:05  com.tencent.mm  [ERROR][App]java.lang.ClassNotFoundException: com.tencent.tinker.lib.tinker.TinkerApplicationHelper
de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:12)
net.ankio.auto.xposed.hooks.wechat.WechatHooker.closeTinker(WechatHooker.kt:221)
net.ankio.auto.xposed.hooks.wechat.WechatHooker.hookLoadPackage(WechatHooker.kt:69)
net.ankio.auto.xposed.core.App.initHooker(App.kt:267)
net.ankio.auto.xposed.core.App.access$initHooker(App.kt:54)
net.ankio.auto.xposed.core.App$handleLoadPackage$1.invoke(App.kt:135)
net.ankio.auto.xposed.core.App$handleLoadPackage$1.invoke(App.kt:134)
net.ankio.auto.xposed.core.App.hookAppContext$onCachedApplication(App.kt:90)
net.ankio.auto.xposed.core.App.access$hookAppContext$onCachedApplication(App.kt:54)
net.ankio.auto.xposed.core.App$hookAppContext$hookApplication$1.invoke(App.kt:106)
net.ankio.auto.xposed.core.App$hookAppContext$hookApplication$1.invoke(App.kt:100)
net.ankio.auto.xposed.core.hook.Hooker$after$1.afterHookedMethod(Hooker.kt:103)
de.robv.android.xposed.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
J.callback(Unknown Source:292)
LSPHooker_.attachBaseContext(Unknown Source:11)
com.tencent.mm.app.Application.attachBaseContext(Unknown Source:0)
android.app.Application.attach(Application.java:346)
android.app.Instrumentation.newApplication(Instrumentation.java:1288)
android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1404)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:7150)
android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2280)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loopOnce(Looper.java:205)
android.os.Looper.loop(Looper.java:294)
android.app.ActivityThread.main(ActivityThread.java:8417)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)

2024-11-27 13:25:05  com.tencent.mm  [INFO][App]Adaptation Info:{remittance.model=com.tencent.mm.plugin.remittance.model.g1, luckymoney.model=com.tencent.mm.plugin.luckymoney.model.n5}
2024-11-27 13:25:05  HookerEnvironment  [INFO][App]InitHooker: 微信, AutoVersion: 4.0.0-Canary.20241121032305 - Xposed, Application: /data/app/~~ry4mFQxm9GxKYO9fgbRXZA==/com.tencent.mm-L2SwpNRLDhOqk-hSLxgTdA==/base.apk
2024-11-27 13:25:05  com.tencent.mm  [INFO][WechatHooker]tinkerDir: /data/user/0/com.tencent.mm/tinker
2024-11-27 13:23:18  net.ankio.auto.xposed  [INFO][LanguageUtils.kt(33)]App Language: SYSTEM => zh
2024-11-27 13:23:09  net.ankio.auto.xposed  [INFO][FloatingWindowService.kt(107)]BillInfo：BillInfoModel(id=170, type=Income, currency='CNY', money=11.0, fee=0.0, time=1732684987000, shopName='X', shopItem='你已收款，资金已存入零钱', cateName='外快 - 好评返现', extendData='', bookName='默认账本', accountNameFrom='支付宝', accountNameTo='', app='com.tencent.mm', groupId=-1, channel='微信[转账收款]', state=Wait2Edit, remark='X - 你已收款，资金已存入零钱', auto=false, ruleName='微信转账')
2024-11-27 13:23:09  net.ankio.auto.xposed  [INFO][FloatingWindowService.kt(115)]parent：null
2024-11-27 13:23:09  net.ankio.auto.xposed  [INFO][FloatingWindowService.kt(81)]FloatingWindowService Start，Timeout：10 s
2024-11-27 13:23:09  net.ankio.auto.xposed  [INFO][FloatingWindowService.kt(106)]Server start => Intent { cmp=net.ankio.auto.xposed/net.ankio.auto.service.FloatingWindowService (has extras) }, From = JsRoute
2024-11-27 13:23:09  AutoServer  [INFO][]拉起自动记账悬浮窗口：Intent { flg=0x50810000 cmp=net.ankio.auto.xposed/net.ankio.auto.ui.activity.FloatingWindowTriggerActivity (has extras) }
2024-11-27 13:23:09  AutoServer  [INFO][]自动记录 - 关闭: BillInfoModel(id=170, type=Income, currency='CNY', money=11.0, fee=0.0, time=1732684987000, shopName='X', shopItem='你已收款，资金已存入零钱', cateName='外快 - 好评返现', extendData='', bookName='默认账本', accountNameFrom='支付宝', accountNameTo='', app='com.tencent.mm', groupId=-1, channel='微信[转账收款]', state=Wait2Edit, remark='X - 你已收款，资金已存入零钱', auto=false, ruleName='微信转账')
2024-11-27 13:23:09  AutoServer  [INFO][]账单: BillInfoModel(id=170, type=Income, currency='CNY', money=11.0, fee=0.0, time=1732684987000, shopName='X', shopItem='你已收款，资金已存入零钱', cateName='外快 - 好评返现', extendData='', bookName='默认账本', accountNameFrom='支付宝', accountNameTo='', app='com.tencent.mm', groupId=-1, channel='微信[转账收款]', state=Wait2Edit, remark='X - 你已收款，资金已存入零钱', auto=false, ruleName='微信转账')
2024-11-27 13:23:09  AutoServer  [INFO][]自动分组功能状态: true
2024-11-27 13:23:08  AutoServer  [INFO][]识别用时: 50 ms
2024-11-27 13:23:08  AutoServer  [INFO][]执行结果:{"book":"默认账本","category":"外快 - 好评返现"} 
2024-11-27 13:23:08  AutoServer  [INFO][]执行数据: {"type":"Income","money":11.0,"shopName":"X","shopItem":"你已收款，资金已存入零钱","time":"13:23"}
2024-11-27 13:23:08  AutoServer  [INFO][]执行Js:             var window = JSON.parse(data);
            var common=function(t){"use strict";var e={Expend:"Expend",Income:"Income",Transfer:"Transfer"},n={"美元":"USD","阿联酋迪拉姆":"AED","阿富汗尼":"AFN","阿尔巴尼亚列克":"ALL","亚美尼亚德拉姆":"AMD","荷属安的列斯盾":"ANG","安哥拉宽扎":"AOA","阿根廷比索":"ARS","澳大利亚元":"AUD","阿鲁巴弗罗林":"AWG","阿塞拜疆马纳特":"AZN","波斯尼亚马克":"BAM","巴巴多斯元":"BBD","孟加拉塔卡":"BDT","保加利亚列弗":"BGN","巴林第纳尔":"BHD","布隆迪法郎":"BIF","百慕大元":"BMD","文莱元":"BND","玻利维亚诺":"BOB","巴西雷亚尔":"BRL","巴哈马元":"BSD","不丹努尔特鲁姆":"BTN","博茨瓦纳普拉":"BWP","白俄罗斯卢布":"BYN","伯利兹元":"BZD","加拿大元":"CAD","刚果法郎":"CDF","瑞士法郎":"CHF","智利比索":"CLP","人民币":"CNY","哥伦比亚比索":"COP","哥斯达黎加科朗":"CRC","古巴可兑换比索":"CUC","古巴比索":"CUP","佛得角埃斯库多":"CVE","捷克克朗":"CZK","吉布提法郎":"DJF","丹麦克朗":"DKK","多米尼加比索":"DOP","阿尔及利亚第纳尔":"DZD","埃及镑":"EGP","厄立特里亚纳克法":"ERN","埃塞俄比亚比尔":"ETB","欧元":"EUR","斐济元":"FJD","福克兰群岛镑":"FKP","英镑":"GBP","格鲁吉亚拉里":"GEL","根西岛镑":"GGP","加纳塞地":"GHS","直布罗陀镑":"GIP","冈比亚达拉西":"GMD","几内亚法郎":"GNF","危地马拉格查尔":"GTQ","圭亚那元":"GYD","港币":"HKD","洪都拉斯伦皮拉":"HNL","克罗地亚库纳":"HRK","海地古德":"HTG","匈牙利福林":"HUF","印尼盾":"IDR","以色列新谢克尔":"ILS","曼岛镑":"IMP","印度卢比":"INR","伊拉克第纳尔":"IQD","伊朗里亚尔":"IRR","冰岛克朗":"ISK","泽西岛镑":"JEP","牙买加元":"JMD","约旦第纳尔":"JOD","日元":"JPY","肯尼亚先令":"KES","吉尔吉斯斯坦索姆":"KGS","柬埔寨瑞尔":"KHR","基里巴斯元":"KID","科摩罗法郎":"KMF","韩元":"KRW","科威特第纳尔":"KWD","开曼群岛元":"KYD","哈萨克斯坦坚戈":"KZT","老挝基普":"LAK","黎巴嫩镑":"LBP","斯里兰卡卢比":"LKR","利比里亚元":"LRD","莱索托洛蒂":"LSL","利比亚第纳尔":"LYD","摩洛哥迪拉姆":"MAD","摩尔多瓦列伊":"MDL","马达加斯加阿里亚里":"MGA","北马其顿代纳尔":"MKD","缅甸元":"MMK","蒙古图格里克":"MNT","澳门币":"MOP","毛里塔尼亚乌吉亚":"MRU","毛里求斯卢比":"MUR","马尔代夫拉菲亚":"MVR","马拉维克瓦查":"MWK","墨西哥比索":"MXN","马来西亚林吉特":"MYR","莫桑比克梅蒂卡尔":"MZN","纳米比亚元":"NAD","尼日利亚奈拉":"NGN","尼加拉瓜科多巴":"NIO","挪威克朗":"NOK","尼泊尔卢比":"NPR","新西兰元":"NZD","阿曼里亚尔":"OMR","巴拿马巴波亚":"PAB","秘鲁索尔":"PEN","巴布亚新几内亚基那":"PGK","菲律宾比索":"PHP","巴基斯坦卢比":"PKR","波兰兹罗提":"PLN","巴拉圭瓜拉尼":"PYG","卡塔尔里亚尔":"QAR","罗马尼亚列伊":"RON","塞尔维亚第纳尔":"RSD","俄罗斯卢布":"RUB","卢旺达法郎":"RWF","沙特里亚尔":"SAR","所罗门群岛元":"SBD","塞舌尔卢比":"SCR","苏丹镑":"SDG","瑞典克朗":"SEK","新加坡元":"SGD","圣赫勒拿镑":"SHP","塞拉利昂利昂":"SLL","索马里先令":"SOS","苏里南元":"SRD","南苏丹镑":"SSP","圣多美多普拉":"STN","叙利亚镑":"SYP","斯威士兰里兰吉尼":"SZL","泰铢":"THB","塔吉克斯坦索莫尼":"TJS","土库曼斯坦马纳特":"TMT","突尼斯第纳尔":"TND","汤加潘加":"TOP","土耳其里拉":"TRY","特立尼达和多巴哥元":"TTD","图瓦卢元":"TVD","新台币":"TWD","坦桑尼亚先令":"TZS","乌克兰格里夫纳":"UAH","乌干达先令":"UGX","乌拉圭比索":"UYU","乌兹别克斯坦索姆":"UZS","委内瑞拉玻利瓦尔":"VES","越南盾":"VND","瓦努阿图瓦图":"VUV","萨摩亚塔拉":"WST","中非金融合作法郎":"XAF","东加勒比元":"XCD","特别提款权":"XDR","西非金融合作法郎":"XOF","太平洋法郎":"XPF","也门里亚尔":"YER","南非兰特":"ZAR","赞比亚克瓦查":"ZMW","津巴布韦元":"ZWL"};function r(t,e){(null==e||e>t.length)&&(e=t.length);for(var n=0,r=Array(e);n<e;n++)r[n]=t[n];return r}function a(t,e,n){return Object.defineProperty(t,"prototype",{writable:!1}),t}function o(t,e){var n="undefined"!=typeof Symbol&&t[Symbol.iterator]||t["@@iterator"];if(!n){if(Array.isArray(t)||(n=c(t))||e){n&&(t=n);var r=0,a=function(){};return{s:a,n:function(){return r>=t.length?{done:!0}:{done:!1,value:t[r++]}},e:function(t){throw t},f:a}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}var o,i=!0,l=!1;return{s:function(){n=n.call(t)},n:function(){var t=n.next();return i=t.done,t},e:function(t){l=!0,o=t},f:function(){try{i||null==n.return||n.return()}finally{if(l)throw o}}}}function i(t,e){return function(t){if(Array.isArray(t))return t}(t)||function(t,e){var n=null==t?null:"undefined"!=typeof Symbol&&t[Symbol.iterator]||t["@@iterator"];if(null!=n){var r,a,o,i,c=[],l=!0,u=!1;try{if(o=(n=n.call(t)).next,0===e){if(Object(n)!==n)return;l=!1}else for(;!(l=(r=o.call(n)).done)&&(c.push(r.value),c.length!==e);l=!0);}catch(t){u=!0,a=t}finally{try{if(!l&&null!=n.return&&(i=n.return(),Object(i)!==i))return}finally{if(u)throw a}}return c}}(t,e)||c(t,e)||function(){throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.")}()}function c(t,e){if(t){if("string"==typeof t)return r(t,e);var n={}.toString.call(t).slice(8,-1);return"Object"===n&&t.constructor&&(n=t.constructor.name),"Map"===n||"Set"===n?Array.from(t):"Arguments"===n||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n)?r(t,e):void 0}}function l(){var t=arguments.length>0&&void 0!==arguments[0]?arguments[0]:"",e=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"";if(13===t.length)return parseInt(t);if(0===t.length)return 1e4*Math.floor(Date.now()/1e4);if(!e.match(/[YMDhis]+/g))throw new Error("Invalid format string");var n=e.replace(/Y/g,"(\\d{2,4})").replace(/M/g,"(\\d{1,2})").replace(/D/g,"(\\d{1,2})").replace(/h/g,"(\\d{1,2})").replace(/i/g,"(\\d{1,2})").replace(/s/g,"(\\d{1,2})"),r=t.match(new RegExp("^".concat(n,"$")));if(!r)throw console.log(n,t,r),new Error("Invalid time format");for(var a=e.match(/[YMDhis]/g),o={},i=0;i<a.length;i++)o[a[i]]=r[i+1];var c=new Date,l={Y:o.Y||c.getFullYear(),M:o.M||c.getMonth()+1,D:o.D||c.getDate(),h:o.h||c.getHours()+8,m:o.i||0,s:o.s||0};return 2===l.Y.length&&(l.Y="20"+l.Y),new Date(l.Y,l.M-1,l.D,l.h,l.m,l.s).getTime()}function u(t){var e=!(arguments.length>1&&void 0!==arguments[1])||arguments[1];if("number"==typeof t)return t;if("string"==typeof t){t=t.replace(/[^\d.]/g,"");var n=parseFloat(t);return isNaN(n)?0:!e&&n<0?-n:n}return 0}function s(t){return+parseFloat(u(t,!(arguments.length>1&&void 0!==arguments[1])||arguments[1]).toFixed(2))}var f=a((function t(){var r=arguments.length>0&&void 0!==arguments[0]?arguments[0]:e.Expend,a=arguments.length>1&&void 0!==arguments[1]?arguments[1]:.01,o=arguments.length>2&&void 0!==arguments[2]?arguments[2]:"",i=arguments.length>3&&void 0!==arguments[3]?arguments[3]:"",c=arguments.length>4&&void 0!==arguments[4]?arguments[4]:"",l=arguments.length>5&&void 0!==arguments[5]?arguments[5]:"",u=arguments.length>6&&void 0!==arguments[6]?arguments[6]:0,s=arguments.length>7&&void 0!==arguments[7]?arguments[7]:n["人民币"],f=arguments.length>8&&void 0!==arguments[8]?arguments[8]:0,h=arguments.length>9&&void 0!==arguments[9]?arguments[9]:"";!function(t,e){if(!(t instanceof e))throw new TypeError("Cannot call a class as a function")}(this,t),this.type=r,this.money=a,this.fee=u,this.shopName=o,this.shopItem=i,this.accountNameFrom=c,this.accountNameTo=l,this.currency=s,this.time=f,this.channel=h})),h={handleContentItems:function(t,e){t.forEach((function(t){switch(t.title){case"交易对象：":case"付款方：":case"付款人：":case"对方账户：":case"Trading partner：":case"Counterparty account：":e.shopName=t.content;break;case"付款方式：":case"退款方式：":case"Payment method：":if("账户余额"===t.content||"Balance"===t.content){e.accountNameFrom="支付宝余额";break}e.accountNameFrom=t.content;break;case"扣款说明：":case"退款说明：":case"转账备注：":e.shopItem=t.content;break;case"还款到：":e.accountNameTo=t.content}}))},handleBillItems:function(t,n){t.forEach((function(t){if(void 0!==t.value){var r=JSON.parse(t.value);switch(t.templateId){case"BLDetailTitle":n.shopName=r.content;break;case"BLDetailPrice":n.money=s(r.amount),n.money<0&&(n.money=-n.money),r.amount.includes("-")?n.type=e.Expend:r.amount.includes("+")?n.type=e.Income:n.type=e.Transfer;break;default:if(void 0===r.data)return;var a=r.data[0].content||"";/创建时间|支付时间/.test(r.title)?n.time=l(a,"Y-M-D h:i:s"):/付款方式/.test(r.title)?(n.accountNameFrom=a,/账户余额/.test(n.accountNameFrom)&&(n.accountNameFrom="支付宝余额")):/商品说明|转账备注/.test(r.title)?n.shopItem=a:/收款方全称|对方账户/.test(r.title)?n.shopName=a:/还款到/.test(r.title)&&(n.accountNameTo=a)}}}))}};return t.AliTools=h,t.BillType=e,t.Currency=n,t.RuleObject=f,t.findNonEmptyString=function(){for(var t=Array.from(arguments),e=0;e<t.length;e++)if(""!==t[e]&&"string"==typeof t[e])return t[e];return""},t.formatDate=l,t.isTimeInRange=function(t,e,n){function r(t){var e=i(t.split(":").map(Number),2);return 60*e[0]+e[1]}var a=r(t),o=r(e),c=r(n);return a<=o?c>=a&&c<=o:c>=a||c<=o},t.parseWechat=function(t,e,n,r){var a=JSON.parse(t).mMap;if(a.source!==n)return null;var c=a.title.replace(/[\d.,]+/g,"");if(!r.includes(c)){var l,u=!1,s=o(r);try{for(s.s();!(l=s.n()).done;){var f=l.value;if(-1!==f.indexOf("*")&&!c.match(f)){u=!0;break}}}catch(t){s.e(t)}finally{s.f()}if(u)return null}return function(t,e,n,r){var a,c=o(e);try{for(c.s();!(a=c.n()).done;){var l=i(a.value,2),u=l[0],s=l[1],f=t.match(u);if(f)return s(f,n,r)}}catch(t){c.e(t)}finally{c.f()}return null}(a.description,e,a.t,a)},t.splitSms=function(t){var e=JSON.parse(t),n=e.body.match(/^【(.*?)】(.*)$/);if(n){var r=i(n,3),a=r[1],o=r[2];return{sender:e.sender,bankName:a,text:o,t:e.t}}var c=e.body.match(/^(.*)【(.*?)】$/);if(c){var l=i(c,3),u=l[1],s=l[2];return{sender:e.sender,bankName:s,text:u,t:e.t}}throw new Error("不支持处理的消息格式")},t.stripHtml=function(t){return t.replace(/<[^>]*>/g,"")},t.toDoubleFloat=function(t){return s(u(t)/100)},t.toFloat=s,t.transferCurrency=function(t){return"RMB"===t?"CNY":n[t]||"CNY"},t}({});

            function getCategory(money,type,shopName,shopItem,time){ if(shopName.indexOf("华北电力大学")!==-1  && shopItem.indexOf("自助设备消费")!==-1 ){ return { book:'默认账本',category:'校园卡'} }
if(shopName.indexOf("长沙云多啦信息技术有限公司")!==-1 ){ return { book:'默认账本',category:'校园卡'} }

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
同 #772
