### ISSUE TITLE
微信支付获取不到商户名称

### ISSUE THREAD

**Issue by LanFeng11** [AutoAccountingOrg/AutoAccounting#79]
已知扫码付款，数据中获取不到商户名称

**Comment by AnkioTomas** [comment]
版本？

**Comment by LanFeng11** [comment]
> 版本？
beta6
规则0.2

**Comment by LanFeng11** [comment]
> 版本？

![Uploading Screenshot_2024-04-30-13-55-47-923_net.ankio.auto.xposed.jpg…]()

**Comment by AnkioTomas** [comment]
好的，先标记为bug，我记得修过这个问题

**Comment by AnkioTomas** [comment]
自动记账和lsp的日志发下
