### ISSUE TITLE
日志输出调整

### ISSUE THREAD

**Issue by AnkioTomas** [AutoAccountingOrg/AutoAccounting#808]
只有严重错误才输出到xposed，其他直接输出到自动记账

**Comment by lamprose** [comment]
> 只有严重错误才输出到xposed，其他直接输出到自动记账

https://github.com/AutoAccountingOrg/AutoAccounting/blob/213db06030154543485ec0f55a5e40d5c68fd7e0/app/src/main/java/net/ankio/auto/xposed/core/logger/Logger.kt#L65
这儿是不是也应该调整判断一下是否打开了调试模式

**Comment by AnkioTomas** [comment]
> > 只有严重错误才输出到xposed，其他直接输出到自动记账
> 
> https://github.com/AutoAccountingOrg/AutoAccounting/blob/213db06030154543485ec0f55a5e40d5c68fd7e0/app/src/main/java/net/ankio/auto/xposed/core/logger/Logger.kt#L65
> 
> 
> 这儿是不是也应该调整判断一下是否打开了调试模式

这里不需要，因为是异常，异常需要输出到xp来的
异常通常不会携带敏感信息

**Comment by lamprose** [comment]
> > > 只有严重错误才输出到xposed，其他直接输出到自动记账
> > 
> > 
> > https://github.com/AutoAccountingOrg/AutoAccounting/blob/213db06030154543485ec0f55a5e40d5c68fd7e0/app/src/main/java/net/ankio/auto/xposed/core/logger/Logger.kt#L65
> > 
> > 这儿是不是也应该调整判断一下是否打开了调试模式
> 
> 这里不需要，因为是异常，异常需要输出到xp来的 异常通常不会携带敏感信息

上一行不是已经输出异常信息到xp了吗 打开调试模式相当于输出详细异常信息 这样看起来不更合理吗

**Comment by AnkioTomas** [comment]
> > > > 只有严重错误才输出到xposed，其他直接输出到自动记账
> > > 
> > > 
> > > https://github.com/AutoAccountingOrg/AutoAccounting/blob/213db06030154543485ec0f55a5e40d5c68fd7e0/app/src/main/java/net/ankio/auto/xposed/core/logger/Logger.kt#L65
> > > 
> > > 这儿是不是也应该调整判断一下是否打开了调试模式
> > 
> > 
> > 这里不需要，因为是异常，异常需要输出到xp来的 异常通常不会携带敏感信息
> 
> 上一行不是已经输出异常信息到xp了吗 打开调试模式相当于输出详细异常信息 这样看起来不更合理吗

这里输出的是堆栈信息，也就是异常的调用链，光有异常的message有时候很难定位问题。

**Comment by lamprose** [comment]
> > > > > 只有严重错误才输出到xposed，其他直接输出到自动记账
> > > > 
> > > > 
> > > > https://github.com/AutoAccountingOrg/AutoAccounting/blob/213db06030154543485ec0f55a5e40d5c68fd7e0/app/src/main/java/net/ankio/auto/xposed/core/logger/Logger.kt#L65
> > > > 
> > > > 这儿是不是也应该调整判断一下是否打开了调试模式
> > > 
> > > 
> > > 这里不需要，因为是异常，异常需要输出到xp来的 异常通常不会携带敏感信息
> > 
> > 
> > 上一行不是已经输出异常信息到xp了吗 打开调试模式相当于输出详细异常信息 这样看起来不更合理吗
> 
> 这里输出的是堆栈信息，也就是异常的调用链，光有异常的message有时候很难定位问题。

嗯嗯 我的理解是提交报错日志不应该打开调试模式复现错误后提交吗 可能我的理解有误吧

**Comment by AnkioTomas** [comment]
> > > > > > 只有严重错误才输出到xposed，其他直接输出到自动记账
> > > > > 
> > > > > 
> > > > > https://github.com/AutoAccountingOrg/AutoAccounting/blob/213db06030154543485ec0f55a5e40d5c68fd7e0/app/src/main/java/net/ankio/auto/xposed/core/logger/Logger.kt#L65
> > > > > 
> > > > > 这儿是不是也应该调整判断一下是否打开了调试模式
> > > > 
> > > > 
> > > > 这里不需要，因为是异常，异常需要输出到xp来的 异常通常不会携带敏感信息
> > > 
> > > 
> > > 上一行不是已经输出异常信息到xp了吗 打开调试模式相当于输出详细异常信息 这样看起来不更合理吗
> > 
> > 
> > 这里输出的是堆栈信息，也就是异常的调用链，光有异常的message有时候很难定位问题。
> 
> 嗯嗯 我的理解是提交报错日志不应该打开调试模式复现错误后提交吗 可能我的理解有误吧

那是理想情况。
实际上很多人都是勉强能用就行.....
