### ISSUE TITLE
建议支持 GitHub access token 以解决 API 限流问题

### ISSUE THREAD

**Issue by TrioTea** [AutoAccountingOrg/AutoAccounting#810]
### 描述建议

建议加入用户可选填写并使用access token，解决从github api检查更新的限流问题，类似于Obtainium这样的操作
![1733385485979_d](https://github.com/user-attachments/assets/1699c6c3-b344-4c8f-a110-400a5cc138ab)

### 该功能带来的好处或者优点

```bash
目前从github检查更新由于受到GitHub api 60/h的限制，非常容易出现“API rate limit exceeded”
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该功能尚未被报告。

**Comment by AnkioTomas** [comment]
感觉好像没那个必要，自动记账检查更新的频率并不高，我记得好像有1小时缓存来着

**Comment by TrioTea** [comment]
> 感觉好像没那个必要，自动记账检查更新的频率并不高，我记得好像有1小时缓存来着

也是有道理的，一般也不影响使用。
只是之前每次看日志的时候，以及手动检查规则更新的时候，都比较容易出现检查更新的错误，我初步定位的原因应该是api的限流问题
