### ISSUE TITLE
偶现一笔交易出现两次弹窗

### ISSUE THREAD

**Issue by TrioTea** [AutoAccountingOrg/AutoAccounting#815]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

一笔交易出现两次弹窗

### 重现步骤

```bash
暂时没有确定复现步骤，会持续关注，补充信息
```

### 相关环境说明

自动记账：[4.0.0-Canary.20241205_2022](https://github.com/AutoAccountingOrg/AutoAccounting/releases/tag/4.0.0-Canary.20241205_2022)
Lsposed：1.7.2-7279
安卓：15

### 日志内容

[log.log](https://github.com/user-attachments/files/18032035/log.log)

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
可是根据你给我的log来看好像只拉起了一次悬浮窗

**Comment by TrioTea** [comment]
> 可是根据你给我的log来看好像只拉起了一次悬浮窗

是的，我也看到了，不过确实出现了两次悬浮窗
昨天我也发现了一次，我还以为是我错觉，我再遇到会仔细注意相关信息

**Comment by AnkioTomas** [comment]
> > 可是根据你给我的log来看好像只拉起了一次悬浮窗
> 
> 是的，我也看到了，不过确实出现了两次悬浮窗 昨天我也发现了一次，我还以为是我错觉，我再遇到会仔细注意相关信息

你是解锁之后弹了2次吗？

我这边发现可能是因为，锁屏状态下，弹窗的intent没有发送到自动记账，解锁后系统才让这个intent发送到了自动记账，但是此时自动记账又拉起了没记录的账单，导致了重复

**Comment by TrioTea** [comment]
好像是的，解锁之后看到有弹窗

**Comment by AnkioTomas** [comment]
对悬浮窗这一块做了重构，不知道会不会引入新的bug

**Comment by TrioTea** [comment]
这个问题好像还需要修复

**Comment by AnkioTomas** [comment]
fixed in https://github.com/AutoAccountingOrg/AutoAccounting/releases/tag/4.0.0-Canary.20241223_2021
