### ISSUE TITLE
识别支付是哪个APP产生的，优先使用该APP规则

### ISSUE THREAD

**Issue by z1298808165** [AutoAccountingOrg/AutoAccounting#830]
### 描述建议

希望可以判断是哪个APP产生的消费，或者其它更好或可行的方法，现在自动记账是监听各个APP消息通知的不知道能不能做区分

场景1：有时候使用支付宝用银行卡付钱，但是微信因为绑定了这个银行卡，所以再消费的时候微信的银行公众号也会有个通知，这个时候会出发两次规则记账

场景2：再支付宝使用银行卡还款的时候会记为转账（已有规则），但是因为微信也会收到银行公众号的消息通知，所以这个时候会触发一个消费（已有规则）

### 该功能带来的好处或者优点

```bash
不用重复弹出记账窗口，也不会产生错误类型的记账
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该功能尚未被报告。

**Comment by AnkioTomas** [comment]
关掉一个规则就好了
就算高速你是哪个app产生的消息也会不可避免的产生重复账单
此外，自动记账设置里面可以开启规则显示

**Comment by z1298808165** [comment]
> 关掉一个规则就好了 就算告诉你是哪个app产生的消息也会不可避免的产生重复账单 此外，自动记账设置里面可以开启规则显示

好的好的，不过我意思是 不知道能不能做到识别出是哪个APP产生的消费，这样就可以直接这个APP的规则（如果对应APP没有规则则再使用其他APP产生的通知来匹配规则），这样即使多个APP接收到了来自同一次消费的消息通知 也不会产生重复记账

**Comment by TrioTea** [comment]
同一笔交易，不同的通知渠道引起的多次悬浮窗，感觉可能是重复账单的匹配问题，而不是优先使用哪个App对应规则的问题
例如在淘宝消费了，支付宝和微信绑定的对应公众号都会有消费的提示，正常来说，最先匹配到的规则会调起悬浮窗，而后边匹配的规则一般就进入“重复账单”的逻辑，应该不会调起悬浮窗。

**Comment by AnkioTomas** [comment]
但是交易类型不一样，会认为是两个账单，而不是重复账单
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by TrioTea** [comment]
> 但是交易类型不一样，会认为是两个账单，而不是重复账单
> —————————
> Ankio 敬上
> ***@***.***
> 若无闲事挂心头，便是人间好时节。
> 
> 

这个场景确实是这样，支付宝是转账，但是对于银行来说都是支出
