### ISSUE TITLE
[Bug][Rule][DATA]com.eg.android.AlipayGphone

### ISSUE THREAD

**Issue by williammmmmmmmm** [AutoAccountingOrg/AutoAccounting#832]
## 规则
支付宝消费
## 说明
这个是支付宝用卡支付，怎么识别成微信了
## 数据
[数据过期时间：2025-02-09 10:50:55](https://fars.ee/GTc_)

**Comment by AnkioTomas** [comment]
不是规则的问题，检查你的资产映射

**Comment by williammmmmmmmm** [comment]
确实是映射的问题，感谢
