### ISSUE TITLE
自定义分类规则，条件匹配文本过多时无法保存

### ISSUE THREAD

**Issue by xuwei112** [AutoAccountingOrg/AutoAccounting#833]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

自定义分类规则想用正则匹配，当一次输入文本太多时无法保存规则

### 重现步骤

```bash
1.自定义分类规则
2.右下角添加
3.选择条件-商户-正则匹配到-输入内容
4.内容过多则选择账本和分类按钮会被文本顶到下面且该界面无法滑动，导致无法保存规则
```

### 相关环境说明

自动记账版本:4.0.0-Canary.20241205__2022
安卓版本:12
钱迹版本：4.1.2-965

### 日志内容

无

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by xuwei112** [comment]
![1733712703129](https://github.com/user-attachments/assets/08505136-933c-410e-80fa-304d79b29664)
![1733712703140](https://github.com/user-attachments/assets/3129741c-e0f6-4dcd-860d-e760c4c1d84e)
如图所示，该界面无法下滑，当输入文本过多时，选择账本和分类无法保存

**Comment by TrioTea** [comment]
这个就很像在重写AutoRule的默认分类了
