### ISSUE TITLE
[Bug][Rule][DATA]com.tencent.mm

### ISSUE THREAD

**Issue by ID-say** [AutoAccountingOrg/AutoAccounting#849]
## 规则
微信转账
## 说明
看不懂，但是似乎没有这个账单
## 数据
[数据过期时间：2025-02-16 10:49:17](https://fars.ee/5mbd)

**Comment by AnkioTomas** [comment]
凡是可以点反馈的都一定是识别到了账单，如果你找不到，很有可能被自己删了
