### ISSUE TITLE
请教各位大佬，no root怎么使用啊

### ISSUE THREAD

**Issue by Vision-Wong** [AutoAccountingOrg/AutoAccounting#857]
### 问题

手机是小米14，虽然目前这个机子还可以解BL锁，后面预载HyperOS目前解不了。而且手机上有不少资料。因此请教一下，不root怎能用这个插件。lspatch好像要修改所有需要调用支付app的应用，用起来很麻烦。

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该问题尚未被报告。

**Comment by AnkioTomas** [comment]
只需要修补微信 支付宝 钱迹，保持微信后台持续运行即可

**Comment by Vision-Wong** [comment]
> 只需要修补微信 支付宝 钱迹，保持微信后台持续运行即可

好的，我尝试一下，请问这样插件运行成功了吗？我试了转账给别人，没有自动记账。
![微信截图_20241220172323](https://github.com/user-attachments/assets/56a1a4cb-e50a-453b-9add-c710d65cdd89)
![微信截图_20241220172252](https://github.com/user-attachments/assets/a5d48601-9c47-4e93-b9d5-47868b7e9bdd)

**Comment by Vision-Wong** [comment]
> 只需要修补微信 支付宝 钱迹，保持微信后台持续运行即可

![微信截图_20241223094858](https://github.com/user-attachments/assets/2dca9b8c-a376-4443-9bba-54b9a152f9aa)
请教大佬，重新patch了3个应用，模块作用域这些都配置好了之后，能正常读取到微信支付宝数据，但是都没配对规则，请问是哪里还需要设置吗？

**Comment by AnkioTomas** [comment]
> > 只需要修补微信 支付宝 钱迹，保持微信后台持续运行即可
> 
> ![微信截图_20241223094858](https://private-user-images.githubusercontent.com/188284726/398030424-2dca9b8c-a376-4443-9bba-54b9a152f9aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDIyMDksIm5iZiI6MTczNDk0MTkwOSwicGF0aCI6Ii8xODgyODQ3MjYvMzk4MDMwNDI0LTJkY2E5YjhjLWEzNzYtNDQ0My05YmJhLTU0YjlhMTUyZjlhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwODE4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzI3YjEyYzM1NjVjYWRiZTg1OWIyZjI0ZjkyY2ExNzFmMzNmYzE2ZDMyYWRjOGY4MzA1YmM3NWRmODc5ODRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JDpgX3A1riaS1ImWZXup1OP7DHnVJy1qsO20R948N6s) 请教大佬，重新patch了3个应用，模块作用域这些都配置好了之后，能正常读取到微信支付宝数据，但是都没配对规则，请问是哪里还需要设置吗？

首页右上角看看日志呗，日志显示没匹配就是没规则咯

**Comment by czxinshui** [comment]
不要用beta版

**Comment by Vision-Wong** [comment]
> > > 只需要修补微信 支付宝 钱迹，保持微信后台持续运行即可
> > 
> > 
> > ![微信截图_20241223094858](https://private-user-images.githubusercontent.com/188284726/398030424-2dca9b8c-a376-4443-9bba-54b9a152f9aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDIyMDksIm5iZiI6MTczNDk0MTkwOSwicGF0aCI6Ii8xODgyODQ3MjYvMzk4MDMwNDI0LTJkY2E5YjhjLWEzNzYtNDQ0My05YmJhLTU0YjlhMTUyZjlhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwODE4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzI3YjEyYzM1NjVjYWRiZTg1OWIyZjI0ZjkyY2ExNzFmMzNmYzE2ZDMyYWRjOGY4MzA1YmM3NWRmODc5ODRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JDpgX3A1riaS1ImWZXup1OP7DHnVJy1qsO20R948N6s) 请教大佬，重新patch了3个应用，模块作用域这些都配置好了之后，能正常读取到微信支付宝数据，但是都没配对规则，请问是哪里还需要设置吗？
> 
> 首页右上角看看日志呗，日志显示没匹配就是没规则咯

自动分类规则定义了，官方规则也更新了之后还是不能记账，请问还有哪里要设置一下吗？
![Screenshot_2024-12-25-13-18-06-749_net ankio auto lspatch](https://github.com/user-attachments/assets/1eafca53-9faf-4c66-8aaf-4671b0c1e890)
![Screenshot_2024-12-25-13-14-41-587_net ankio auto lspatch](https://github.com/user-attachments/assets/bb6ae472-6b78-4289-8300-346c35bc86c0)

**Comment by Vision-Wong** [comment]
> 不要用beta版

现在换了最新的,Canary版本，还没实现自动记账，可能还有些设置没到位

**Comment by AnkioTomas** [comment]
上传数据等适配，看起来就是单纯的没规则而已

**Comment by Vision-Wong** [comment]
> 上传数据等适配，看起来就是单纯的没规则而已

好的，目前适配了哪些支付方式呢？我这这是扫码付款的数据。

**Comment by AnkioTomas** [comment]
https://github.com/AutoAccountingOrg/AutoRule/tree/master/src/rule/com.eg.android.AlipayGphone/app

**Comment by Vision-Wong** [comment]
> https://github.com/AutoAccountingOrg/AutoRule/tree/master/src/rule/com.eg.android.AlipayGphone/app

大佬，提交适配后，现在可以自动记账了，但账单没办法同步到钱迹，需要一个一个点开按保存才同步过去，请问这是正常的吗？
![Uploading Screenshot_2024-12-27-20-02-38-279_net.ankio.auto.lspatch.jpg…]()
![Uploading Screenshot_2024-12-27-20-02-52-679_net.ankio.auto.lspatch.jpg…]()

**Comment by Vision-Wong** [comment]
![Uploading Screenshot_2024-12-27-20-02-52-679_net.ankio.auto.lspatch.jpg…]()

**Comment by Vision-Wong** [comment]
刚更新12271415之后，一个个弹窗连续蹦出来，然后就同步过去了……是修复了这个bug了吗？权限我都给够了的

**Comment by lyj0309** [comment]
安卓15 lspatch 微信闪退了，我看已经停更了，有啥别的方案吗

**Comment by AnkioTomas** [comment]
> 安卓15 lspatch 微信闪退了，我看已经停更了，有啥别的方案吗

https://ez-book.org/pages/start/#%E5%85%8D-root-%E7%94%A8%E6%88%B7%E6%8E%A8%E8%8D%90

**Comment by lyj0309** [comment]
> > 安卓15 lspatch 微信闪退了，我看已经停更了，有啥别的方案吗
> 
> https://ez-book.org/pages/start/#%E5%85%8D-root-%E7%94%A8%E6%88%B7%E6%8E%A8%E8%8D%90

尝试使用 [LSPatch-JingMatrix](https://github.com/JingMatrix/LSPatch) ，显示patch成功了 ，也更新规则了，但是微信转账了没有匹配到

**Comment by lyj0309** [comment]
应该是能匹配到，但是程序没反应，直接炸了
![Screenshot_2025-01-03-09-24-42-979_net ankio auto lspatch](https://github.com/user-attachments/assets/e6037a0e-1b4f-4892-acfc-baeb750c9de0)
![Screenshot_2025-01-03-09-21-29-135_net ankio auto lspatch](https://github.com/user-attachments/assets/8f8f9232-82ce-46f2-a73d-f546b593b5c6)

**Comment by AnkioTomas** [comment]
不要用便携模式

**Comment by AnkioTomas** [comment]
写了不看？https://ez-book.org/pages/active/#_1-%E4%BF%AE%E8%A1%A5%E5%BA%94%E7%94%A8

**Comment by lyj0309** [comment]
没有用便携模式
![Screenshot_2025-01-03-09-34-17-898_org lsposed lspatch](https://github.com/user-attachments/assets/601875ae-0a01-48bf-bb8d-0d606bcef352)

**Comment by AnkioTomas** [comment]
集成就是便携，要用本地

**Comment by lyj0309** [comment]
感谢大佬，好使了，建议更新一下文档或者加个app检测模式的功能

**Comment by lyj0309** [comment]
感谢大佬，好使了，建议更新一下文档或者加个app检测模式的功能

**Comment by lyj0309** [comment]
大佬，我看文档说 `如遇第三方应用无法调用微信，请[使用dia模块修补并伪造签名](https://ez-book.org/pages/active/)
`  有具体方法吗，不是很懂，是`dialog`模块吗，但我看只支持lsposed
