### ISSUE TITLE
微信输入框调起输入法多次失败

### ISSUE THREAD

**Issue by TrioTea** [AutoAccountingOrg/AutoAccounting#881]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

微信输入框调起输入法多次失败

### 重现步骤

```bash
1. 状态解锁
2. 打开微信，尝试打开输入法输入消息，输入法会多次自动收起
```

### 相关环境说明

自动记账：[4.0.0-Canary.20241226_0214](https://github.com/AutoAccountingOrg/AutoAccounting/releases/tag/4.0.0-Canary.20241226_0214)
LSP：1.9.2-it(7287)
安卓：15 小米14U HP-OS2

### 日志内容

```log
2024-12-26 15:59:39  net.ankio.auto.xposed  [INFO][LanguageUtils.kt(33)]App Language: SYSTEM => zh
2024-12-26 15:59:36  net.ankio.auto.xposed  [ERROR][Logger.kt(129)]startFloatService error: t is invalid, 0

2024-12-26 15:59:35  net.ankio.auto.xposed  [ERROR][Logger.kt(129)]startFloatService error: t is invalid, 0

2024-12-26 15:59:34  net.ankio.auto.xposed  [ERROR][Logger.kt(129)]startFloatService error: t is invalid, 0

2024-12-26 15:59:33  net.ankio.auto.xposed  [ERROR][Logger.kt(129)]startFloatService error: t is invalid, 0

2024-12-26 15:59:32  net.ankio.auto.xposed  [ERROR][Logger.kt(129)]startFloatService error: t is invalid, 0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by TrioTea** [comment]
看了一下这个日志的代码来自AutoAccounting\app\src\main\java\net\ankio\auto\ui\activity\FloatingWindowTriggerActivity.kt
不过似乎涉及到intent传递，看不太懂

**Comment by AnkioTomas** [comment]
应该不是这个日志导致的吧，这个是为了修复重复拉起悬浮窗的问题引入了时间变量，1分钟之前的intent会被忽略掉。

**Comment by TrioTea** [comment]
> 应该不是这个日志导致的吧，这个是为了修复重复拉起悬浮窗的问题引入了时间变量，1分钟之前的intent会被忽略掉。

我试了一下，解锁之后打开自动记账App，也会出现自动退出的问题，我录屏发你邮件看看，自动记账的日志和LSP的日志我暂时都没看到什么可能有用的（奇怪）

**Comment by AnkioTomas** [comment]
> > 应该不是这个日志导致的吧，这个是为了修复重复拉起悬浮窗的问题引入了时间变量，1分钟之前的intent会被忽略掉。
> 
> 我试了一下，解锁之后打开自动记账App，也会出现自动退出的问题，我录屏发你邮件看看，自动记账的日志和LSP的日志我暂时都没看到什么可能有用的（奇怪）

ankio@ankio.net

此外，我觉得你应该重启手机试下，t不应该=0，只有服务端代码没更新才有可能出现这个情况

**Comment by TrioTea** [comment]
> > > 应该不是这个日志导致的吧，这个是为了修复重复拉起悬浮窗的问题引入了时间变量，1分钟之前的intent会被忽略掉。
> > 
> > 
> > 我试了一下，解锁之后打开自动记账App，也会出现自动退出的问题，我录屏发你邮件看看，自动记账的日志和LSP的日志我暂时都没看到什么可能有用的（奇怪）
> 
> [ankio@ankio.net](mailto:ankio@ankio.net)
> 
> 此外，我觉得你应该重启手机试下，t不应该=0，只有服务端代码没更新才有可能出现这个情况

重启过的，目前是百分百复现的，我一会儿尝试回退一下之前用得较久的一个LSP版本，观察下是不是LSP更新引起的

**Comment by AnkioTomas** [comment]
> > > > 应该不是这个日志导致的吧，这个是为了修复重复拉起悬浮窗的问题引入了时间变量，1分钟之前的intent会被忽略掉。
> > > 
> > > 
> > > 我试了一下，解锁之后打开自动记账App，也会出现自动退出的问题，我录屏发你邮件看看，自动记账的日志和LSP的日志我暂时都没看到什么可能有用的（奇怪）
> > 
> > 
> > [ankio@ankio.net](mailto:ankio@ankio.net)
> > 此外，我觉得你应该重启手机试下，t不应该=0，只有服务端代码没更新才有可能出现这个情况
> 
> 重启过的，目前是百分百复现的，我一会儿尝试回退一下之前用得较久的一个LSP版本，观察下是不是LSP更新引起的

我觉得不是

**Comment by TrioTea** [comment]
确实不是，降级之后，问题没有被解决

**Comment by TrioTea** [comment]
@AnkioTomas 我把自动记账里的账单数据清了，问题就被解决了
在这之前，我试过了卸载重装，也不可以

**Comment by AnkioTomas** [comment]
fixed
