### ISSUE TITLE
小米hypos2下，应用一直在加载。lsposed正常启动加载

### ISSUE THREAD

**Issue by yadanchina** [AutoAccountingOrg/AutoAccounting#886]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

进去应用一直加载数据

### 重现步骤

```bash
1.直接进入自动记账应用
2.点击所有功能，都在加载数据
3.lsposed已成功加载
```

### 相关环境说明

钱迹更新到最新
maskgisk-alpha（28101）
zygisk-lsposedv1.10.1(7115)

### 日志内容

日志也加载不出来

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by AnkioTomas** [comment]
检查lsp勾选和lsp日志
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。

**Comment by AnkioTomas** [comment]
使用这个版本再测试看看https://github.com/AutoAccountingOrg/AutoAccounting/releases/tag/4.0.0-Canary.20241230_0854

**Comment by yadanchina** [comment]
> 使用这个版本再测试看看https://github.com/AutoAccountingOrg/AutoAccounting/releases/tag/4.0.0-Canary.20241230_0854

修复完成，
设置完成，第一次重启手机。显示lopsed加载完成。但是一直再加载
又进行了一次重启手机现在正常。

**Comment by AnkioTomas** [comment]
第一次重启后可能是因为短信服务那个时候还没拉起来，理论上等一会就好了
—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。
