### ISSUE TITLE
在游戏等应用中，不调起弹窗

### ISSUE THREAD

**Issue by TrioTea** [AutoAccountingOrg/AutoAccounting#891]
### 描述建议

在游戏等应用中，可以设置是否需要调起弹窗
如果选择不调起弹窗，可以进行自动记账，采用Toast或是通知消息进行提醒

### 该功能带来的好处或者优点

```bash
目前在游戏过程中，如果出现后台扣款的情况，在调起弹窗的这一过程中，会导致游戏中断，改变亮度等情况。
如果可以设置一些特殊APP可以执行自选操作的话，或许体验会好一些
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该功能尚未被报告。

**Comment by AnkioTomas** [comment]
直接加个选项：【横屏勿扰】是不是合理一点。
看剧、打游戏基本都是横屏

**Comment by TrioTea** [comment]
> 直接加个选项：【横屏勿扰】是不是合理一点。 看剧、打游戏基本都是横屏

有道理，【横屏勿扰】更合适，打游戏基本上都是横屏
