### ISSUE TITLE
开启了账单去重,同一笔账单,出现多次识别,并未去重

### ISSUE THREAD

**Issue by zfqit** [AutoAccountingOrg/AutoAccounting#895]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

开启了账单去重,同一笔账单,出现多次识别,并未去重

### 重现步骤

```bash
1. 开启账单去重
2. 打开微信账单
```

### 相关环境说明

自动记账版本: 4.0.0-Canary.20241130151026
lsp 版本 1.9.2
安卓版本: 安卓 13

### 日志内容

录屏
https://github.com/user-attachments/assets/b98ed486-2530-4326-b3a3
日志
[log.txt](https://github.com/user-attachments/files/18278652/log.txt)
-34c689d8621d

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/AutoAccountingOrg/AutoAccounting/issues)，以确保该错误尚未被报告。

**Comment by zfqit** [comment]
https://github.com/user-attachments/assets/2869f737-f30f-41c4-80f3-a81d657a8ade

**Comment by zfqit** [comment]
上述版本填错,以下才是正确的版本
自动记账版本: 4.0.0-Canary.20241230_1416

**Comment by AnkioTomas** [comment]
因为两个问题导致的
1. 时间识别错误
2. 微信不知道为什么重复调用了6次接口请求数据
将在下个版本修复
